### ISSUE TITLE
FIP: Add the NonEmpty property type wrapper

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#113]
`NonEmpty`is currently used by `semigroups` recently introduced in `base`. it's defined as a normal cons without a empty constructor:

```haskell
data NonEmpty a = a :| [a]
```

Proposing a NonEmpty property to replace it:

```haskell
newtype NonEmpty a = NonEmpty a

nonEmpty :: Collection a => a -> Maybe (NonEmpty a)
nonEmpty a | null a = Nothing
           | otherwise = Just a
-- Maybe could be a Partial, or we could add nonEmpty_ that throws ...
```

Advantages:

* Works for any collection: `NonEmpty (UArray Word8)`, `NonEmpty String`
* use a smart constructor to make sure only non empty collection are created

As a disadvantage:

* Doesn't deconstruct the first element by construction like the current one, so appear less inherently safe. e.g. `data NonEmpty a = NonEmpty a (Collection a)`

This open the door for many functions to become safer and non partial (but *not* by construction):

```haskell
minimum :: Collection a => NonEmpty a -> Element a
maximum :: Collection a => NonEmpty a -> Element a
head :: Collection a => NonEmpty a -> Element a
last :: Collection a => NonEmpty a -> Element a
uncons :: Collection a => NonEmpty a -> (Element a, a)
foldl1 ...
foldl1' ...
foldr1 ...
```

**Comment by ndmitchell** [comment]
I like it - I don't consider the "not obvious safety" to be a negative at all - it doesn't actually make it any safer in any observable way.

**Comment by parsonsmatt** [comment]
The [PureScript approach](https://github.com/purescript-contrib/purescript-nonempty) is rather nice:

```haskell
data NonEmpty f a = NonEmpty a (f a)
```

Or, by taking advantage of GADTs,

```haskell
data NonEmpty f where
  NonEmpty :: Element f -> f -> NonEmpty f
```

This guarantees by construction that you have a non-empty container and is generic over containing types.

**Comment by vincenthz** [comment]
@parsonsmatt I think, this is exactly what I was hinting to when I say it's not "by construction safe". What you're proposing is nice and is indeed safe by construction, but it has 3 major disadvantages:

* It deconstruct the collection, which mean `NonEmpty` suddenly have an impact on runtime, compared to have no impact. it's quite list centric
* All the operations on NonEmpty need to be reimplemented considering one of the element of the collection is split apart. it's usually trivial, but we can't just reuse the container's operation. for example `sum`
* Non-empty doesn't necessarily mean you're going to use the head element. `last` is a good counterexample (skew toward list again, as obviously you don't have a choice but to process the head element)
