### ISSUE TITLE
Chunks is just []

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#12]
Admittedly with a strict element, but calling it StrictList might be a better name? Or maybe it has sufficiently little value that it's unnecessary.

**Comment by vincenthz** [comment]
I think the only reason to have `Chunks` (I'm not attached to the name in any case), is to be able to define a type that works on content of content:

```haskell
type Element [[a]] = a              -- what it suppose to mean
type Element (Chunks a) = a
```

with the same interface (take, drop, splitAt, ...)

It's not possible to do with `[[a]]` since we already have:

```haskell
type Element [a] = a
```

**Comment by ndmitchell** [comment]
Chunks is just `[]` so I'm not sure how `Element (Chunks a)` and `Element [[a]]` are related. It sounds like you want a "see through the concat" type of elements, but then perhaps `newtype Concat a = Concat a` and:

    type Element (Concat a) = Element (Element a)

Is the way to go, and you can work on `[Vector a]`, e.g. a lazy streaming vector.

**Comment by vincenthz** [comment]
Yes, the `Concat` would do a similar job. However in term of API, I'm not sure that give a nice result e.g.:

```haskell
take :: Int -> Concat [Vector a] -> (Concat [Vector a], Concat [Vector a])
```

seems less straighforward than :

```haskell
take :: Int -> Chunks (Vector a) -> (Chunks (Vector a), Chunks (Vector a))
```

Only difference I can think of is that with the `Concat` approach, you're not limited to have your chunk represented as List, but you could have `Concat (Vector (Vector a))`. Maybe both would make sense..

**Comment by ndmitchell** [comment]
To me, the `Concat` formulation seems clearer. But even if you do want `Chunks`, maybe type Chunks a = Concat [a]` is the way to go, since that makes the semantics clear.

Note that no one will ever have the type signature you specified above - it's only going to exist as an instance of a generic class, and thus only in peoples heads.

**Comment by vincenthz** [comment]
Chunks is gone, it will be replaced very likely be replaced by a Concat semantic type
