### ISSUE TITLE
Use the hashable library

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#121]
Hashable is the standard Hashing typeclass. If you duplicate the Hashable typeclass you are no longer compatible with anything that provides or consumes hashes. If you reuse it, you can pick things like unordered-containers off the shelf, and consume libraries that already define Hashable definitions.

In practice, I hope Hashable moves over to the base library at some point in the future, but until then, working with the standard one certainly has benefits.

**Comment by vincenthz** [comment]
Just a quick brain dump related to this:

* It certainly should have moved to base by now :(
* The functionality of hashable will be in foundation at some point. supplemented with the ability to choose your hash method (not have one hardcoded), or at least to distinguish keyed hashing and non-keyed.
* It's very likely the unordered-container types will be there too. personally I really want good hashtable support in the near future.
* From my PoV, I'm fine depending on hashable provided it's temporary:
    1) we should make a list of the hashable things (like unordered-container) that would be nice to have before removing. I don't think it would be a long list
    2) I think putting everything behind some cabal flag so that we can still build without dependencies would be good and that it's clearly easy to remove in the future

**Comment by ndmitchell** [comment]
To be fair, Hashable is the kind of place where a crypto expert might have a lot to add to the current design, so you reimplementing Hashable might make sense...

**Comment by NicolasDP** [comment]
I don't think we want to add dependencies to `bytestring` and `text`. It seems like defeating the purpose of the library... I believe this should go in [foundation-edge](https://github.com/haskell-foundation/foundation-edge)

**Comment by NicolasDP** [comment]
this would obviously make orphan instances... but providing this is a temporary solution...

**Comment by ndmitchell** [comment]
I had forgotten that hashable was above bytestring/text, when it clearly should have been a dependency of them :(. I think the sensible design answer to this question is "no".

**Comment by vincenthz** [comment]
hashable as a functionality is extremely small. it would probably take ~2 hours to port or have the same functionality, so depending on what you want out of this, this can be done really quickly.

**Comment by ndmitchell** [comment]
For something like hashable what you want is to have the compatibility - so libraries which provide hashable instances can be used directly. However, it seems hashable is a uniquely terrible thing to depend on, given the large dependencies and lack of maintainers - so closing this as a bad idea.
