### ISSUE TITLE
Use fundeps rather than associated types in Tuple

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-foundation/foundation#123]
Hi, what's the opinion of the author(s) on functional dependencies vs. associated types? IMO, associated types are very useful for documentation purposes, but can unnecessarily pollute the type namespace, too.

I wonder if e.g.

``` haskell
class Fstable a b | a -> b where ...
instance Fstable (a, b) a where ...
```

would be better than the current

``` haskell
class Fstable a where
  type FstTy a
  ...

instance Fstable (a, b) where
  type FstTy (a, b) = a
  ...
```

so as to elide the `FstTy` name.

**Comment by vincenthz** [comment]
This is an interesting question, I didn't realize that the associated type would be part of the outside API. This is slightly unfortunate and at least we should think of exportable names. Related to changing it to fundeps, I can think of two issues :

* MPTC and fundeps are not as friendly in my opinion (subjective)
* The type family approach can works without having variable (i.e. work for monomorphic stuff too), for example:

```haskell
data Point = Point Int Int
instance Fstable Point where
   type FstTy Point = Int
   fst (Point x _) = x
```

**Comment by mitchellwrosen** [comment]
> MPTC and fundeps are not as friendly in my opinion (subjective)

Agreed, except in cases like this (overloading a well-named function for convenience) I tend to actually prefer them

> The type family approach can works without having variable

So does the MPTC approach!

```haskell
instance Fstable Point Int where
  fst (Point x _) = x
```

**Comment by vincenthz** [comment]
yes, I realized an hour after posting this that my second point was inaccurate.

So to illustrate the difference on the use site:

Type Family:
```haskell
myFct :: Fstable a => a -> FstTy a
```

MPTC+Fundeps:
```haskell
myFct :: Fstable a b => a -> b
```

Apart from the associated type name (`FstTy`) that I think we should change, anyone want to comment whether they prefer one or the other ?

**Comment by ndmitchell** [comment]
I often read types skipping the context. If you do that with the fun dep it makes little sense. I'm not sure if that matters though.

**Comment by vincenthz** [comment]
ok, so concluding on this, I think the problem with fundeps is that they don't appear in the type anywhere in the usage, making it less than obvious that `b` depends on `a`, so going with associated family type is better I think.

I change the type `FstTy` to `ProductFirst` to prevent some types name which looks a bit too garbled, into something a bit more obvious which I think make (some) sense to export properly. `ProductFirst (a,b)` should make sense in a signature hopefully.

**Comment by Toxaris** [comment]
Why use different names for the same concepts? The module is called "Tuple", but the associated type uses "Product". The value-level class member is called "fst" but the type-level class member uses "First".

I would use the following naming convention to signal that this class is all about `fst` and the other names `HasFst` and `Fst` are just collateral):

    class HasFst a where
      type Fst a :: *
      fst :: a -> Fst a

Other naming conventions work fine, too. But the current names appear more random than conventional.

**Comment by mitchellwrosen** [comment]
It's true that 

```haskell
fst :: HasFst a b => a -> b
```

at first glance looks less informative than

```haskell
fst :: HasFst a => a -> Fst a
```

in that ignoring the context at least gives you some information. But, I'd argue this convention doesn't scal well at all. A popular usage of these types of classes is overloaded lenses. Simplifying to just overloaded getters, consider:

```haskell
fst :: HasFst a => a -> Fst a
snd :: HasSnd a => a -> Snd a
foo :: HasFoo a => a -> Foo a
bar :: HasBar a => a -> Bar a
baz :: HasBaz a => a -> Baz a
oink :: HasOink a => a -> Oink a
```

In each case we are polluting the type namespace with a name that gives no more information than the function name itself, i.e. the name `foo` should be enough to tell you that it gets a "foo" thing out. So, I still think MPTCs are the right call here. It's what `makeClassy` and stuff from `Control.Lens.TH` generates.

**Comment by Toxaris** [comment]
There is a constant overhead of one additional name per overloaded getter, so this scales well enough, in a sense.

I wonder whether the extra name can be helpful in error messages.

**Comment by mitchellwrosen** [comment]
I think scale was the wrong word - I meant to say that if you apply this pattern liberally everywhere you might end up using up good names for types, type families, etc.

**Comment by Toxaris** [comment]
Some experiments with ghci, first with type families:

```
> :set -XTypeFamilies
> class HasFst a where type Fst a; fst :: a -> Fst a
> class HasSnd a where type Snd a; snd :: a -> Snd a

> :t fst
fst :: HasFst a => a -> Fst a

> :t fst . snd . fst
fst . snd . fst
  :: (HasSnd (Fst a), HasFst (Snd (Fst a)), HasFst a) =>
     a -> Fst (Snd (Fst a))

> :t \x -> fst x == snd x
\x -> fst x == snd x
  :: (Snd a ~ Fst a, HasSnd a, HasFst a, Eq (Fst a)) => a -> Bool
```

Now the same with functional dependencies:

```
> :set -XMultiParamTypeClasses
> :set -XFunctionalDependencies
> class HasFst a b | a -> b where fst :: a -> b
> class HasSnd a b | a -> b where snd :: a -> b

> :t fst
fst :: HasFst a b => a -> b

> :t fst . snd . fst
fst . snd . fst
  :: (HasSnd a1 a, HasFst a2 a1, HasFst a c) => a2 -> c

> :t (\x -> fst x == snd x)
(\x -> fst x == snd x)
  :: (HasSnd a1 a, HasFst a1 a, Eq a) => a1 -> Bool
```

I like neither :(

**Comment by mitchellwrosen** [comment]
Right, neither compose particularly nicely, but you typically use these things one-off on a concrete type, and not necessarily as reusable top-level exports.

**Comment by vincenthz** [comment]
@Toxaris I didn't use `Fst`, and `Snd` because I didnt want to pollute the type namespace with short types (3 characters), that don't do that much, that also doesn't scale to 4 (`Fth`), 5 (`Fth` ?),. .., and is not *that* useful (the concept is fairly limited, only a product getter)

One thing I want to add is, that going forward, `Nth` from `Foundation.Tuple.Nth` is the only typeclass that I would want exposed replacing all Fst, Snd, ...
