### ISSUE TITLE
platform dependent & C bits

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#126]
It's very likely we'll have C functions/bindings (random, timing, C fast function for certain types) and some need for some platform/detection features.

I'm thinking it would be nicer to create a `foundation-platform` (name not set in stone) that `foundation` would use. `foundation-platform` would contains all the nitty gritty C functions and bindings to what we need in one place, and expose strictly lowlevel haskell function.

it will prevent mixing all the lowlevel bits and annoying Setup.hs detection, etc. from other higher level bits.

**Comment by ndmitchell** [comment]
I don't see the advantages... You still have the same issues, you just have to introduce an artificial divide. I also think platform is a bad name because of the exiting Haskell platform.

**Comment by vincenthz** [comment]
So there's the obvious division disadvantage, but as advantages:

* foundation can ship with a normal `Setup.hs`. the system detection which are extremely fiddly and make cabal do crazy things (like use this Setup everytime you recompile anything)
* foundation can ship with no cbits. I've seen cabal do silly things like recompiling the C bits everytime you relink anything in cryptonite
* the C bits are the only things which have symbols that are not versioned like the rest of haskell. it's easier to clash C symbols if you iterate quickly on a library. if those C bits are separated, then as I don't expect much change generally there, there would be a large span of foundation versions that will use one specific foundation C package.

**Comment by ndmitchell** [comment]
From what it sounds like users lives will be simpler without two packages, but developers lives might be simpler with. If there are actual cabal/stack bugs here, perhaps they could be linked to make sure they are upstream? If they were fixable easy, it might tip the balance.

**Comment by vincenthz** [comment]
we can revisit the discussion later as needed, but for now, we just carry on adding to the main repo
