### ISSUE TITLE
segv in UTF8 string while stressing the Sequential interface

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#127]
easy to reproduce for me with:

    stack test --test-arguments "--quickcheck-tests 40000 -p foundation/String/UTF8/Sequential/Sequential"

Last few lines looks like (2 differents segv runs):

```
         intersperse:                        OK (2.69s)
            +++ OK, passed 40000 tests.
          intercalate:                        test-foundation: internal error: scavenge_one: strange object 7807024
    (GHC version 7.10.3 for x86_64_apple_darwin)


          intersperse:                        test-foundation: internal error: scavenge_one: strange object 0
```

(not necessarily linked to intercalate, or intersperse)

**Comment by JanGe** [comment]
Should be fixed in commit https://github.com/haskell-foundation/foundation/pull/124/commits/9fc78d8bc512139b687aa1d906865cd669863d6e. We were writing out of bounds in `intersperse`.

@ndmitchell suggested adding invariants with Liquid Haskell.

**Comment by vincenthz** [comment]
great, thanks for fixing !

I'm not sure about liquid haskell (never used, only vaguely looked at it), but we need "a thing" to catch those things early in the future.

The immediate solution I'm thinking is adding all bound checks for all the unsafe bits in testing mode through some CPP.

**Comment by snoyberg** [comment]
How about using assert and have Travis include a configuration with
optimizations turned off?

**Comment by vincenthz** [comment]
yes, the assert thing is what I mean by bounds check in the unsafe bits.

**Comment by snoyberg** [comment]
I just meant you can avoid the CPP ugliness by having both optimized and
unoptimized builds. Assertions are always ignored in optimized builds.

**Comment by vincenthz** [comment]
I was thinking using a simple:

```haskell
#if DEBUG
boundCheck a b =...
#else 
boundCheck _ _ = False
#endif
{-# INLINE boundCheck #-}
```

and then use `boundCheck` in the primitive code without sprinkling the code with CPP stuff.
I'm happy using `assert` too.

**Comment by JanGe** [comment]
I wanted to look into how much effort would have been needed to have Liquid Haskell catch that bug. Unfortunately, I can't even get it to run:

```
$ stack exec liquid -- Foundation/String/UTF8.hs -v
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.
[...]
Foundation/Internal/IsList.hs:15:21:
     error: token is not a valid binary operator in a preprocessor subexpression
#if MIN_VERSION_base(4,7,0)
    ~~~~~~~~~~~~~~~~^
1 error generated.
liquid: liquid: phase `C pre-processor' failed (exitcode = 1)
```

Does anyone know, how I could make Liquid Haskell aware of the macro definitions in `.stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/autogen/cabal_macros.h`?
