### ISSUE TITLE
Add Base64

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#138]

**Comment by vincenthz** [comment]
Base16 is already available, so removing from title

**Comment by jship** [comment]
Is Base64 needed in core `foundation` still?

I see that `memory` already has it:  https://github.com/vincenthz/hs-memory/blob/de90409f682ef4abae4897f286ad5ea1cfc8a917/Data/ByteArray/Encoding.hs#L45

**Comment by NicolasDP** [comment]
still missing the base64
