### ISSUE TITLE
Foldable methods are not visible.

### ISSUE THREAD

**Issue by AnthonyJacob** [haskell-foundation/foundation#140]
``` haskell
 Foundation> :i Foldable
    class Foldable (t :: * -> *) where
      Data.Foldable.fold :: Monoid m => t m -> m
      Data.Foldable.foldMap :: Monoid m => (a -> m) -> t a -> m
      Data.Foldable.foldr :: (a -> b -> b) -> b -> t a -> b
      Data.Foldable.foldr' :: (a -> b -> b) -> b -> t a -> b
      Data.Foldable.foldl :: (b -> a -> b) -> b -> t a -> b
      Data.Foldable.foldl' :: (b -> a -> b) -> b -> t a -> b
      Data.Foldable.foldr1 :: (a -> a -> a) -> t a -> a
      Data.Foldable.foldl1 :: (a -> a -> a) -> t a -> a
      Data.Foldable.toList :: t a -> [a]
      Data.Foldable.null :: t a -> Bool
      Data.Foldable.length :: t a -> Int
      Data.Foldable.elem :: Eq a => a -> t a -> Bool
      Data.Foldable.maximum :: Ord a => t a -> a
      Data.Foldable.minimum :: Ord a => t a -> a
      Data.Foldable.sum :: GHC.Num.Num a => t a -> a
      Data.Foldable.product :: GHC.Num.Num a => t a -> a
```

Is this a bug or is the Foldable class not yet fully implemented?

**Comment by JanGe** [comment]
The core `Foundation` module currently re-exports `Data.Foldable` without exporting its methods (which probably wasn't intended => bug).

Foundation also has its own `Foldable` type class in `Foundation.Collection.Foldable`. If you want to use that (and some of the other collection type classes), you have to import `Foundation.Collection`.

**Comment by JanGe** [comment]
@AnthonyJacob I think we should keep this open as a bug until we export `foldr`, `foldl`, etc. from the base module as other people trying to use Foundation in its current state might run into this.

**Comment by vincenthz** [comment]
yes, the export of base's Foldable is a bug now that we have a better integrated foundation's Foldable. It was fine to get us started before, but now clearly bad.

**Comment by AnthonyJacob** [comment]
Btw the same goes for Traversable, but that is probably because it is not implemented yet.
