### ISSUE TITLE
Remove type signatures from method names.

### ISSUE THREAD

**Issue by AnthonyJacob** [haskell-foundation/foundation#141]
I am of the opinion that **method** names should be as general as possible while only **function** names should contain information about types they operate on (if needed):

``` haskell
-- methods
class Functor f where
    map :: ...  

class Monoid  m where
    empty :: ...
    append :: ...

-- functions
mapList     :: (a -> b) -> [a] -> [b]

emptyList   :: [a]
appendList  :: [a]      -> [a] -> [a]
```

Because chances are, you will be working much more often with methods than ordinary functions...

EDIT:
Type signature in name is the `f` in `fmap`, `m` in `mappend` or `List` in `emptyList`.

**Comment by vincenthz** [comment]
I'm not sure I understand what is this about; care to explain in more detail how is that suppose to work, and practically what you are suggesting ? (I really don't get how a method's class without signature works ?)

**Comment by AnthonyJacob** [comment]
@vincenthz Oh you misunderstood my post. Should have made it more clear. :)

**Comment by vincenthz** [comment]
related to #144 

In principle I like the idea, but I think this is going to be a major pain and akin to burning perhaps unnecessary bridges with base.

**Comment by AnthonyJacob** [comment]
In retrospect I think it is much nicer to use the same name for all types. You can always use `List.map`, `List.empty` etc when needed.
