### ISSUE TITLE
Change meaning of [  ]

### ISSUE THREAD

**Issue by Josef-Vonasek** [haskell-foundation/foundation#157]
I was checking the Collection.md API presentation. And I was wondering whether it is possible to change the meaning of `[ ]` to not symbolize lists but `Collection` type class instead.
``` haskell


NOW                         THEN  
`Element c -> c -> c`       `e -> [e] -> [e]` 
`[a]`                       `List a`
```

**Comment by vincenthz** [comment]
There's no way to overload (or rebind) the list at the type level. we only have OverloadedList at the value level.
