### ISSUE TITLE
Add `strict` family of functions

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#16]
strict2 f !x !y = f x y

Could be useful?

**Comment by vincenthz** [comment]
Considering how many space leaks are generally present in haskell, I think anything that lower the bar to evaluate things sounds like a win. it would be nice to tie this up somehow with `$!` (which would be `strict1`). any thoughts ?

**Comment by ndmitchell** [comment]
I thin strict1 is just a synonym - no need to tie it up as far as I can see.

**Comment by vincenthz** [comment]
I wasn't thinking of `strict1` but more about some clues that `strict2` is figuratively speaking `$!!`, `strict3` .. `$!!!` ?

**Comment by ndmitchell** [comment]
I would have strict1 for consistency. Making strict2 an operator seems confusing, since its operating on things it isn't being passed.

**Comment by sgraf812** [comment]
A potential issue I see with the current implementation (e.g. `strict2 f !a !b = f a b`) is in the presence of partial application. Example GHCI session:
```
Prelude> :set -XBangPatterns
Prelude> let strict1 f !a = f a
Prelude> let strict2 f !a !b = f a b
Prelude> let strict2' f = strict1 (strict1 f)
Prelude> strict2 const undefined `seq` putStrLn "hi"
hi
Prelude> strict2' const undefined `seq` putStrLn "hi"
*** Exception: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at <interactive>:6:13 in interactive:Ghci5
```

I'd expect `strict2'`s semantics rather than `strict2`s.
