### ISSUE TITLE
Indexing strings

### ISSUE THREAD

**Issue by ezyang** [haskell-foundation/foundation#165]
I was curious to know if foundation purposely left out indexing operations on strings. If you're going UTF-8, it's tough to implement these without being O(n), but they still seem useful to have.

**Comment by vincenthz** [comment]
do you mean getting a n'th character in a string (`Int -> String -> Maybe Char`) ?

**Comment by ezyang** [comment]
Yep (and related operations.)

**Comment by vincenthz** [comment]
yes, it's indeed missing. can you list the other operations you're thinking about ?

**Comment by ezyang** [comment]
Well, the obvious type class to add is `IndexedCollection`
