### ISSUE TITLE
String type features

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#17]
Features I'd like from the `String` type:

* Small strings should be moveable on the heap so they don't cause excessive fragmentation.
* Large strings should be pinned in memory so they don't cause excessive GC time.
* In certain applications I might want to never use large strings (or set the threshold much higher) - particularly long running server applications where fragmentation is likely to build. Controlling this with an environment variable seems reasonable (e.g. you can put it in a CAF so it doesn't add much overhead).
* I want to be able to create a `String` from a memory mapped file, without copying the string. At the moment that requires creating a `String` from a `Ptr`, but happy with other formulations.

**Comment by vincenthz** [comment]
I generally agree with those goals. I think the env variable is a really nice idea. the `UVector` is now able to be either unpinned or pinned depending on size, the `String` is not yet a newtype of a `UVector` but it's an easy change.

The only problem is handling the mmap part. so it's easy to distinguish between pinned or unpinned memory without having any type difference (both `Bytearray#`), but mmap would be based on `Addr#` (e.g. `Ptr`, `ForeignPtr`).

There's the following options:

1) Make `UVector` a sum type : `UVectorHs PinnedStatus ByteArray# | UVectorForeign Addr#)`. `String` remain unchanged as a `newtype String = String (UVector Word8)`
2) Add a `ForeignVector` that is the same as a `UVector` but only have an `Addr#`
    1) Make `String` a sum type : `UVector | FVector`
    2) Add a `ForeignString` that support the same operation as `String` but work on a `ForeignVector`

In a perfect world I would just choose 1), but I can see some value distinguishing MMap handling which bring all sort of difference with ByteArray#, also the memory cost of having this sum type everywhere.

**Comment by ndmitchell** [comment]
Making String as newtype over Array/Vector seems like a good idea - 0 cost conversions would be great - then having Vector have all the optimisations above would be great. You could always do:

    newtype UVector = UVector (Pinned|Unpinned|Addr) ByteArray# Addr#

Since for both Pinned and Addr you'll have a valid `Addr#` field, and for Unpinned and Pinned you'll have a valid `ByteArray#`.

**Comment by ndmitchell** [comment]
Hmm, maybe you need a finaliser in the `Addr#` part as well - so maybe a `ForeignPtr ()` instead.

**Comment by vincenthz** [comment]
you don't have a valid ByteArray# when it come from foreign memory; The only I think would be possible would be to reuse an empty bytearray# as placeholder that would not be used in the case of an Addr backed Addr#.

also when I say `Addr#`, I'm talking about the general familly of `Ptr`, `ForeignPtr`. I think it's likely to have some kind of finalizer, although I think we could optimise where it's attached to (so not necessarily a `ForeignPtr`)

**Comment by ndmitchell** [comment]
I did mean a placeholder empty ByteArray. But I wonder if you are overestimating the cost of alternatives - with pointer tagging they are pretty cheap, and if you are going to switch on the Pinned/Unpinned anyway, you might get constructor specialisation as well. Then you could have pinned/unpinned/foreign being entirely separate cases, all nicely optimised.

**Comment by vincenthz** [comment]
The Foreign part create lots of headache: the ForeignPtr interface and the more internal Weak# part need IO; so that leave only a `Addr#` / `Ptr` direct interface with having to be careful to not return a `String` or `Vector` that still reference this `Ptr` (otherwise segfault or really bad behavior guaranteed)

**Comment by ndmitchell** [comment]
Ok, sounds like ForeignString and ForeignVector should be separate.

**Comment by ndmitchell** [comment]
I guess being explicit with these special things is advisable.

**Comment by vincenthz** [comment]
There's only one valid case that would be interesting is this case: ghc's primitive string type (e.g. `"abc"#` which is a `Addr#`) and does need a finalizer as it is the binary's executable loaded in memory.

**Comment by ndmitchell** [comment]
That makes me come back to a real alternative data type. There are lots of special cases so just shove each one in an alternative.

**Comment by vincenthz** [comment]
just to make sure when you mean real alternative you mean different type (`ForeignVector` and `ForeignString`) right ?

**Comment by ndmitchell** [comment]
More data Vector = Address Addr | Ptr Ptr | Const ....

**Comment by vincenthz** [comment]
`Addr#` and `Ptr` is effectively the same thing (`Ptr` is just the phantom-typed lifted version of `Addr#`).
So it's possible to to bring an alternative to have:
```
    data UVector = UVectorBA ByteArray# | UVectorAddr Addr#
```
However this would just to allow unlifted string (".."#), as the `ForeignPtr` part need to be in IO to remain safe. Obviously it could be to do the following unsafe things too:

```
withForeignPtr fptr $ \ptr -> do
   let v = UVectorAddr (.. ptr)
   do..vector..operation v
   return something (<-- if something contains a vector / string created there, BAD)
```

**Comment by ndmitchell** [comment]
I had assumed you'd do roughly:

    data UVector a = BA ByteArray# | FP (ForeignPtr ())

And then:

    take n (BA ba) = ...
    take n (FP fp) = unsafePerformIO $ withForeignPtr $ ...

**Comment by ndmitchell** [comment]
Note the vector library offers these different interfaces, but puts them in different types - which I'm unconvinced helps programmers.

**Comment by vincenthz** [comment]
ok, I think I managed to wrangle all the types in place, and now Vector can be backed by an Addr#, Ptr along with the usual ByteArray. all the testing remain to be done

**Comment by ndmitchell** [comment]
Awesome! Was ranting to @snowleopard in the pub last night about how everything was all broken but you were going to fix it :)

**Comment by ndmitchell** [comment]
BTW, looking through https://github.com/vincenthz/hs-foundation/blob/master/Core/Vector/Unboxed.hs I couldn't find the place where you make decisions of switch based on pinned/unpinned. Is it necessary to store that info?

**Comment by vincenthz** [comment]
I wish that was true (fixing all the broken); We'll see, it's certainly fun to try

The switch is at: https://github.com/vincenthz/hs-foundation/blob/master/Core/Vector/Unboxed.hs#L254
For now it doesn't actually switch anything, but just need to choose a value and put the env variable override.

For the pinned / unpinned, it's necessary to store for later; right now it's not used, but as soon as we passing data back and forth handle/socket/... it's going to be necessary to distinguish what can be safely passed as is, from the things that need to be copied before.

**Comment by snowleopard** [comment]
> I wish that was true (fixing all the broken)

@vincenthz No backsies! @ndmitchell convinced me, after two pints, that you'll fix everything, so I'm optimistic :) Happy to help too as a guinea pig.

**Comment by vincenthz** [comment]
Thanks @snowleopard. In term of helping, there's a lot to small and big tasks; either think of what you want to have (create issue, add code, rethink something), or try to use foundation as a prelude+text+vector+.. replacement on any project and report what's missing, not working etc..

**Comment by ndmitchell** [comment]
"on any project" - let me clarify, "on any project that loads of people aren't waiting for and that is not a cross-location collaboration". I was going to start with Hoogle once a checklist is complete.

**Comment by vincenthz** [comment]
well, you can try on anything (in a branch, non-publically, etc), but obviously the bigger / demanding the project, the more unlikely it's going to be easy. Also, it's technically easy to reach out to other libraries (go back to base, or vector, ..) if something is missing in foundation
