### ISSUE TITLE
inaccurate version bounds / compile failure

### ISSUE THREAD

**Issue by hvr** [haskell-foundation/foundation#170]
.cabal file specifies support for `base == 4.*` and `ghc-prim == *`; however, GHC 7.4.2 disagrees:

```
Configuring component lib from foundation-0.0.2
Preprocessing library foundation-0.0.2...

Foundation/String/UTF8.hs:62:18:
    Could not find module `GHC.Char'
    Perhaps you meant GHC.MVar (from base)
    Use -v to see a list of the files searched for.
```

**Comment by NicolasDP** [comment]
thanks for the report.

**Comment by NicolasDP** [comment]
@hvr , thank you for the quick fix on [hackage](http://hackage.haskell.org/package/foundation-0.0.2/revisions/).

**Comment by hvr** [comment]
@NicolasDP you're welcome; fwiw, I noticed because today `memory` pulled in a dependency on `foundation`, thereby suddenly breaking several install-plans for GHC <= 7.4.2 across Hackage if you depended on things like `cryptonite` or `tls`
