### ISSUE TITLE
make filter available

### ISSUE THREAD

**Issue by flip111** [haskell-foundation/foundation#177]
Hi i'm a new user of Foundation. I was expecting that there was a filter function, but there wasnt. After investigating i imported Foundation.Collection, but this was not mentioned in the readme. Can it be added to Foundation or add help to readme??

EDIT: maybe Sequential needs to be re-exported

**Comment by NicolasDP** [comment]
Thanks for raising this issue. I think the collection classes (Sequential and co) could be re-rexpoted from the `Foundation` module. I am not against it.

**Comment by vincenthz** [comment]
Thanks @flip111 for the report. I've now re-exported Sequential (as it should have been).
