### ISSUE TITLE
make `all` available

### ISSUE THREAD

**Issue by flip111** [haskell-foundation/foundation#178]
`Data.List.all :: Data.Foldable.Foldable t => (a -> Bool) -> t a -> Bool`

I search for `all` in this repo (on github code search) and also by:

https://www.haskell.org/hoogle/?hoogle=%28a+-%3E+Bool%29+-%3E+t+a+-%3E+Bool

http://hayoo.fh-wedel.de/?query=%28a+-%3E+Bool%29+-%3E+t+a+-%3E+Bool

but foundation is not mentioned on the last two links.

Maybe the `all` function still needs to be implemented?

Another problem is that if i use `all` from Data.List that i get `Data.Foldable.Foldable` which is not the `Foldable` by Foundation

**Comment by NicolasDP** [comment]
It is missing indeed. In foundation it would have its place with the `Foundation.Collection.Foldable` as well as `any` and `or` and `and` and `sum` and `product`.

**Comment by vincenthz** [comment]
thanks @flip111. `any` and `all` are there now.

@NicolasDP I've haven't added `sum` and `product`, I'm not sure they are useful enough and can't be implemented faster than a `fold` anyway (I think)
