### ISSUE TITLE
Be suitable for Hoogle

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#18]
Here's my checklist:

* Strings which work nicely, but pretty minimally
* Vectors which work nicely, but pretty minimally
* Ability to source the above from a memory mapped file
* Ability to read strings in lazy chunks from a file with copying

**Comment by vincenthz** [comment]
only last item is missing now

**Comment by ndmitchell** [comment]
To expand on the last item, I roughly want:

```
openFile :: FilePath -> IO Handle
closeFile :: Handle -> IO ()
readLine :: Handle -> IO String
```

If `readLine` was instead a `readChunk` of some size then I could resplit on lines myself to pipe them into conduit (which is what I do for Lazy.ByteString going into conduit)

**Comment by vincenthz** [comment]
This is really tricky to have the right API here. So I have now 2 other primitives, but it's sorely lacking a better design line..

`fromByteChunks :: [ByteArray] -> [String]`
`foldTextFile :: (String -> a -> IO a) -> a -> FilePath -> IO a`

one thing is that any `Handle -> IO String` is surprisingly tricky to handle, as, if you "pop" too much data from the handle that happen to be in the middle of a UTF8 sequence would need to be "put back" in the handle for the next call to work (as the `String` is a valid chunk of utf8 sequences).. I didn't really find such a capability through the Handle.

**Comment by ndmitchell** [comment]
What I want to do is drive a conduit with pieces of String from a file, which means it has to start from a `Handle` (so conduit can resource manage the file), and it has to be piecewise with conduit controlling the code flow of data. Perhaps:

    stringFromBytes :: ByteArray -> (String, ByteArray)

So you split the initial pieces which are a valid string, then return the trailing pieces. You would guarantee the second ByteArray was < 4 characters. I could then drive this in a loop by prepending the trailing ByteArray to the next chunk and rerunning. In practice the trailing ByteArray will be zero bytes 99% of the time, so the append can be free. You can imagine optimising the 1% case, but I'd suggest waiting to do that until its really needed.

An optimisation that would be useful is that if the input ByteArray ends properly then the resulting String could be literally the ByteArray wrapped with a String ctor, and the thing could do no memory allocation in 99% of cases.

Thinking further, in my case I really want to convert a stream of ByteArray to a stream of String split on `\n`. I would if to do that I should be using a ByteArray split and then unsafely wrapping the pieces in String before passing them on.

**Comment by ndmitchell** [comment]
There are really two pieces of Hoogle where I want to use foundation - reading from a tarball of files of text and memory mapping the result. I tried implementing the first piece at https://gist.github.com/ndmitchell/6828df5eeca3776b32a0420c73dc95ed. I've filed about 8 tickets on the back of it, including performance, correctness, design decisions and missing functions.

**Comment by ndmitchell** [comment]
For the code for reading from a tarball, after #28 and #32 I end up with the profile:

* Core.Array.Unboxed.break - 30.3%
* Main.unpackLBS - 29.2%
* Core.String.UTF8.fromBytes - 18.8%

The second entry can be addressed by #23. The fact `fromBytes` is slow isn't terrible, it seems something that should take a meaningful amount of time. The slow `break` is a bit of a surprise. I looked at the code, and saw `length` was called in each iteration, but changing that doesn't improve the speed - maybe GHC already hoists it anyway. Maybe the predicate is just expensive? In my case the predicate is the normal `== 10`, so maybe you need a special function for matching on a literal? By doing the static argument transformation I can reduce `break` to 26%, but no further - and by that point it looks like pretty good Core, apart from the call into `unsafeIndex`. My guess is that for tight loops the overhead of `unsafeIndex`, is just too high - you probably need to unpack it fully. That might be especially true for slices.

That said, it's not fatal at this level, and I could live with those overheads for now.

**Comment by vincenthz** [comment]
It should be more performant now. `break` should be much faster and not incur the `unsafeIndex` price as much; It can probably be pushed a bit more by optimising the predicate.

`unpackLBS` should be much faster using the `fromForeignPtr` in `Array.Internal`

No further optimisation for `UTF8.fromBytes` yet

**Comment by ndmitchell** [comment]
`break` performance made absolutely no difference - I can't measure a difference either way.

`unpackLBS` slows down by 25%, details given in #23.

I expect `break` to do meaningful computation.

**Comment by ndmitchell** [comment]
#26 is critical for Hoogle. Other than that, it all looks good.

**Comment by ndmitchell** [comment]
Requires #26 and #65.

**Comment by vincenthz** [comment]
I think it should be more or less suitable now. YMMV :-)

**Comment by ndmitchell** [comment]
Thanks! Certainly looks plausible. I'll give it a go at a port when I have some spare time (which is currently scheduled for Christmas, if I get lucky...)
