### ISSUE TITLE
Simple arithmetic without explicit types not possible

### ISSUE THREAD

**Issue by tepf** [haskell-foundation/foundation#190]
This does not compile without explicitly declaring the types of the numbers:

    module Main where

    import Foundation

    main :: IO ()
    main = putStrLn $ show (1 + 2)

Is this on purpose? Because I often times find myself testing certain functions by hand and declaring the type is annoying. I think you can set default instances with pragmas.

**Comment by vincenthz** [comment]
yes, I think you're right it's missing some defaulting.
