### ISSUE TITLE
Add "read" functions

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#195]
The `Read` class tries to be an all singing and dancing parser library, but a terrible one. However, what most people usually want is to convert a `String` to a value, perhaps with an error message. I couldn't find that in foundation yet. I recently found a program which does a disturbing amount of time doing read from String to Double. I imagine foundation code would wipe the floor with that, and serve a useful purpose.

**Comment by vincenthz** [comment]
`Read` is an interesting new can of worms, it's not clear to me right now how to address the problem. Clearly `Read` is terrible, and have too many concepts intertwined for it to be performant. Any idea from which end to look at the problem ?

**Comment by ndmitchell** [comment]
Just converting a String to an atomic number (Int, Double) covers 80% of the use cases. If you're doing anything more you probably don't want to be using Haskell-specified stringification anyway.

**Comment by vincenthz** [comment]
so you're thinking just having : 

```
readInt :: String -> SomethingToRepresentError Int
readDouble :: String -> SomethingToRepresentError Double
```

Otherwise there's the `Foundation.Parser` which goes in the direction of a more generic and performant parser (although we haven't apply the magic performance dust yet)

**Comment by ndmitchell** [comment]
Yep, or with a type class so `Int`/`Double` is gently abstracted over - but I'm not thinking `[a]` would be a member of the type class. Indeed, a parser is useful, but `strtoi` isn't a parser, and shouldn't have to be.

**Comment by vincenthz** [comment]
The basic functionality is here, but clearly the API is very much WIP and will be revisioned for improvement; the 2 big items: reporting errors & able to return a value+offset before end-of-string.
