### ISSUE TITLE
Ditch Arrow

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#2]
Noone likes Arrow. Why not supply first/second as either restricted to Tuple, or over Bifunctor?

**Comment by vincenthz** [comment]
yeah I'm not a fan of Arrow either, I only use the tuple version. I think generalizing to Bifunctor might make the most sense considering the library is generalizing lots of things, but I'm happy with the restricted Tuple version too

**Comment by ndmitchell** [comment]
I personally use Tuple, but I could imagine if Bifunctor had been in the base a bit longer I'd be using that too.

**Comment by vincenthz** [comment]
I removed them for now; pending a proper think about those functions in next releases
