### ISSUE TITLE
Current state of Foundation.

### ISSUE THREAD

**Issue by AnthonyJacob** [haskell-foundation/foundation#202]
What is the current state of Foundation?

Is it dead or just real life kicked in. I can help by using it for my side projects and post here problems I encountered, but that is not enough on its own. I guess promotion of this project in Haskell community  could really help. For example by reporting some interesting progress that has been done each two months or so... ( more attention => more contributors )

Do you have an idea how much has to be yet done to version 1.0? Can you point areas which are completed and which are not? Is foundation somehow connected to DataHaskell.org initiative?

Thank you.

**Comment by NicolasDP** [comment]
These are fairly good questions.

The project is **not dead**, we are working on it as we can, life kicks in as you say.

Unlike `base` we are not planning to have a stable version (_yet_). We believe that Foundation must evolve with the language and what is commonly accepted as _good practice_.

There are some parts that are fairly complete now:

* `Foundation.Collection`;
* `Foundation.Array`;
* `Foundation.String`;
* `Foundation.Random` (and `Foundation.System.Entropy` as well.

There are modules @vincenthz and I are working on before the next release:

* `Handle`;
* `Network`.

These 2 ones have been known to have issue, the interfaces didn't convinced us and they needed quite a lot of re-write.

And new modules not released yet but stable, one of them being `Conduit`.

We are not part of the [DataHaskell](http://www.datahaskell.org/) initiative.

**Comment by NicolasDP** [comment]
Also, we are welcoming helps ! Feel free to create issues, report bugs and propose PRs.

**Comment by AnthonyJacob** [comment]
Cool, in that case it should be mature enough for my needs.

What bugs me though is how do Foundation types play with other packages. For example I need to write some pretty basic parser / serializer deserializer and I have thought I will use Parsec for that, but Parsec uses Text as far as I know (although after browsing the API it seems the only connection to Text is in the import statement).

Where can I expect to run into problems and how big are they going to be?

**Comment by NicolasDP** [comment]
I see, this is right that UTF16 is not the most common encoding for data and files.

You can use Foundation's String. They are UTF8 (certainly most likely to be needed for files serialisation/deserialisaton).

If you want to use parsec, all you will need is to add an instance of Parsec's `Stream` for Foundation's `String` (you will need [uncons](https://www.stackage.org/haddock/nightly-2017-01-17/foundation-0.0.3/Foundation-String.html#v:uncons).

**Comment by NicolasDP** [comment]
It should not be that hard to use Foundation's type for your purpose. You are most likely to have issues when you will want to use Foundation's Classes (Sequential etc...) with other types from other libraries (such as Text or ByteString). Or to convert one from another as we don't provide direct conversion to/from these types.

**Comment by NicolasDP** [comment]
However, we have some workaround in foundation's edge : [Example with ByteString](https://github.com/haskell-foundation/foundation-edge/blob/master/Foundation/Compat/ByteString.hs).

**Comment by michalt** [comment]
I was also recently wondering what's the status of Foundation. If you're looking for contributors or users, it'd be nice to have something more prominent that one could check for "what is the current status" (e.g., milestones or a note in the README).
Btw. are there any larger users of Foundation? (I couldn't really find any on Hackage) Or potential users? (e.g., that are involved in the design) Or is it a bit too early for that?

**Comment by chreekat** [comment]
fwiw, I'm simply watching this repo, and that gives me a fair indication of what's happening with this project.
