### ISSUE TITLE
Conversion function from String to [Char]

### ISSUE THREAD

**Issue by flip111** [haskell-foundation/foundation#210]
Would be good to add a conversion function from `String` to `[char]` because foundation is now incompatible with the base String. And it's easy to run into this problem, `show` helps a little bit but not enough.

**Comment by vincenthz** [comment]
you can already use `fromList` and `toList` on a `String` to convert back and forth with `[Char]`

**Comment by flip111** [comment]
Ah ok, that's good to know !
