### ISSUE TITLE
splitWhen inconsistent with (more lawful) behavior in text

### ISSUE THREAD

**Issue by ezyang** [haskell-foundation/foundation#217]
foundation's current implementation of splitWhen gives an empty list when run on an empty list.  This is in contrast to text's split, which returns a singleton list with an empty string: https://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html#v:split

The often stated justification is that if you have split work this way, then you have the following law `split b (foo <> singleton b <> bar) = split b foo ++ split b bar`. bytestring differs, but the maintainers are thinking of switching: https://github.com/haskell/bytestring/issues/56

**Comment by vincenthz** [comment]
This is an interesting poll on twitter :)

I'll have to look at the details, but I'm partial to returning a non empty list as the better behaviour.

**Comment by ezyang** [comment]
Yes I think non-empty is better.

**Comment by NicolasDP** [comment]
I believe that we are all talking for `splitOn` for foundation.
