### ISSUE TITLE
Repeated break does not work correctly

### ISSUE THREAD

**Issue by ezyang** [haskell-foundation/foundation#218]
Here is a transcript where Foundation has been imported qualified as F:

```
*Str.Foundation> let Just x = F.uncons (F.snd (F.breakElem '9' (F.fromList "aa9a9\154" :: F.String)))
*Str.Foundation> x
('9',"a9\154")
*Str.Foundation> F.breakElem '9' (F.snd x)
("a9\154","")
*Str.Foundation> F.breakElem '9' "a9\154"
("a","9\154")
```

This looks very fishy!

(P.S. I discovered this because I had an implementation of elemIndexes which I was Quickchecking against a version from string)

**Comment by NicolasDP** [comment]
Thanks for the report. I have written a test case implementing the issue.
We will address this soon.
