### ISSUE TITLE
Is the ByteArray synonym worth it?

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#22]
Writing `UArray Word8` helps people learn all pieces of the library faster. And it shows the nice symmetry. I think this is something to show off, rather than hide behind a type alias.

**Comment by vincenthz** [comment]
I don't disagree about it is somewhat unnecessary, but I find `ByteArray` more pleasing to manipulate than `UArray Word8` (which requires to be paren'ed when composed i.e. `Maybe (UArray Word8)` vs `Maybe ByteArray`

**Comment by ndmitchell** [comment]
Agreed, it's certainly more pleasing to use. But it does confer special status to something that is deliberately not special. Your call though - there are arguments both ways.

**Comment by tekul** [comment]
It also clashes with the existing use in the memory package (as a typeclass), which might confuse people.

**Comment by vincenthz** [comment]
fixed by c776fae
