### ISSUE TITLE
Foundation fails to Build on OpenBSD

### ISSUE THREAD

**Issue by adamsteen** [haskell-foundation/foundation#220]
Hi

as the title says, Foundation fails to Build on OpenBSD.

Foundation/Network/HostName.hsc needs
`#include <sys/socket.h>`
[sys/socket.h](http://man.openbsd.org/socket.2) defines AF_INET and others

OpenBSD does not define all the errno's in Foundation/System/Bindings/Posix.hsc
[http://man.openbsd.org/errno.2](http://man.openbsd.org/errno.2)
the following are not defined
Posix.hsc:121: error: 'EBADMSG' undeclared (first use in this function)
Posix.hsc:148: error: 'EMULTIHOP' undeclared (first use in this function)
Posix.hsc:155: error: 'ENODATA' undeclared (first use in this function)
Posix.hsc:160: error: 'ENOLINK' undeclared (first use in this function)
Posix.hsc:165: error: 'ENOSR' undeclared (first use in this function)
Posix.hsc:166: error: 'ENOSTR' undeclared (first use in this function)
Posix.hsc:171: error: 'ENOTRECOVERABLE' undeclared (first use in this function)
Posix.hsc:178: error: 'EOWNERDEAD' undeclared (first use in this function)
Posix.hsc:181: error: 'EPROTO' undeclared (first use in this function)
Posix.hsc:189: error: 'ETIME' undeclared (first use in this function)

I just commented them out and foundation builds fine.

I am happy to help fix this, but i wasn't sure how you wanted to handle things.

Cheers
Adam

**Comment by vincenthz** [comment]
@adamsteen first let me thanks to point this to our attention. I've took steps to install a freebsd vm and will get an openbsd vm running (when I have enough time to go through getting haskell installed on it), to hopefully prevent similar issue in the future.
