### ISSUE TITLE
Fails to build on Centos 6.8

### ISSUE THREAD

**Issue by erikd** [haskell-foundation/foundation#229]
Building with GHC 7.10 on Centos (yeah, I know :)) I get:
```
Configuring foundation-0.0.4...
Building foundation-0.0.4...
Preprocessing library foundation-0.0.4...
Linux.hsc: In function ‘main’:
Linux.hsc:78: error: ‘IN_EXCL_UNLINK’ undeclared (first use in this function)
Linux.hsc:78: error: (Each undeclared identifier is reported only once
Linux.hsc:78: error: for each function it appears in.)
```
The `IN_EXCL_UNLINK` identifier seems to be in `<linux/inotify.h>` which makes it kernel version specific. Centos 6.8 uses linux 2.6.32 (I kid you not).

**Comment by vincenthz** [comment]
centos 6 😭 .. should be fix now :)

**Comment by erikd** [comment]
Yeah, Centos 6 is pretty sad. Thanks for the fix. I'll test tomorrow at work.

**Comment by erikd** [comment]
:+1: Working as expected. Thanks!

**Comment by ndmitchell** [comment]
Any chance of a release incorporating this fix?

**Comment by vincenthz** [comment]
yes, I'm happy to do one. release early, release often specially when it was not building :)
