### ISSUE TITLE
Add way to construct ByteArray from a strict ByteString, perhaps via one of the pointer methods

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#23]
Currently you have to go via a list, which is grim and not performant.

**Comment by vincenthz** [comment]
Definitely not ideal; My plan of action is to do something like:

* Add some conversion function that will get as close as possible from getting the data without depending on bytestring
* Create a `foundation-bridge` library for going all the way to provide bridge between common haskell package like `bytestring` and `text`

**Comment by ndmitchell** [comment]
That sounds like an excellent plan.

**Comment by vincenthz** [comment]
There's an untested `fromForeignPtr` exported in `Core.Array.Internal` now.

it should works, but I'll really test in `foundation-bridge` once it's off the ground

**Comment by vincenthz** [comment]
Also it should just take the result from `toForeignPtr` from `Data.ByteString.Internal`

**Comment by ndmitchell** [comment]
First piece of bad news is that `F.fromForeignPtr . BS.toForeignPtr` segfaults, fixed in #33.

Second piece of bad news is that it's 25% slower than `F.fromList . BS.unpack`, with profiling showing 73% of time ending up in `withFinalPtr` or `withUnsafeFinalPtr`, all bubbling up from inside `fromBytes`. My guess is you have to push the indexing code "upwards" and do a single `withFinalPtr` at the root of these functions, and I'm sure a similar approach is required for `break` too.

**Comment by vincenthz** [comment]
Any chance you can dump the profile of what you are running somewhere ? possibly also the updated hoogle on foundation and how to run myself (first example refer to a C:\\ path)

`withFinalPtr` should be have gone upwards already, `unsafeIndexer` is doing it at the root of the function.

**Comment by ndmitchell** [comment]
Perhaps I should check in the Hoogle examples to an 'example' directory in this repo? Will produce something this evening.

**Comment by ndmitchell** [comment]
[examples.zip](https://github.com/vincenthz/hs-foundation/files/367546/examples.zip)

Here is the TarReader.hs and profile output, when run on the first 100 entries in the tarball from https://hackage.haskell.org/packages/hoogle.tar.gz. I only run on the first 100 entries because the ~120 entry fails - having a UTF8 Lenient would be great to fix that. There are two hotspots:

        break               Core.Array.Unboxed              219       44413    0.2    0.3    19.3   24.0
         withFinalPtr       Core.Primitive.FinalPtr         222       44313   18.3   23.2    19.2   23.7
          splitAt           Core.Array.Unboxed              226       44261    0.3    0.4     0.3    0.4
          unsafePrimFromIO  Core.Primitive.Monad            224       44313    0.0    0.0     0.5    0.0
           unsafePrimCast   Core.Primitive.Monad            225       44313    0.5    0.0     0.5    0.0

And:

        fromBytes           Core.String.UTF8                240       44261   11.3   11.8    73.5   71.8
         isContinuation     Core.String.UTF8Table           264          21    0.0    0.0     0.0    0.0
         getNbBytes         Core.String.UTF8Table           248     1672583    0.5    0.0     0.5    0.0
         withUnsafeFinalPtr Core.Primitive.FinalPtr         242     1669520   12.7    6.9    61.6   59.9
          withFinalPtr      Core.Primitive.FinalPtr         245     1669520   43.3   53.0    47.9   53.0
           unsafePrimFromIO Core.Primitive.Monad            246     1669520    2.6    0.0     4.6    0.0
            unsafePrimCast  Core.Primitive.Monad            247     1669520    2.1    0.0     2.1    0.0
          unsafePrimToIO    Core.Primitive.Monad            243     1669520    1.0    0.0     1.0    0.0
           unsafePrimCast   Core.Primitive.Monad            244     1669520    0.0    0.0     0.0    0.0
         null               Core.Array.Unboxed              241       44261    0.0    0.0     0.0    0.0
          bool#             Core.Internal.Primitive         252        4079    0.0    0.0     0.0    0.0

**Comment by vincenthz** [comment]
I've optimised some stuff all the over the place, reaching a 3x cpu and 3x memory improvement.

`break` is still high up on the list, as the predicate call seems to consume the most; tried to optimise this away with `breakElem`, but I didn't manage to get the `RULES` to fire before the predicate get transformed in a unrecognisable blob.

also on the much faster list should be `fromBytes`, `copyAtRO`

**Comment by ndmitchell** [comment]
Awesome, twice as fast. I played with `breakElem` - actually exporting it and using it directly didn't make it go any faster. When I then specialised it to `Word8` as the type that did speed up, so lack of specialisation might be the issue.

As it happens, an alternative would be to convert it to a string first, then call lines. That might give you more chance to aggressively optimise as there is no predicate.

**Comment by vincenthz** [comment]
yes, it became obvious after further playing that one of the problem is that the PrimType class dictionary is being floated instead of being specialized. I sprinkled some call with specialized and it went somewhat faster. So, the good news is there's definitely some further room for optimisation

**Comment by vincenthz** [comment]
there's now a repo for compatability stuff https://github.com/haskell-foundation/foundation-edge
