### ISSUE TITLE
Add readInt

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#242]
Benchmarking ByteString.readInt vs Foundation.readInteger I get ByteString being 4.5 times faster. But I suspect that's because ByteString only works over Int, not Integer. A readInt is probably needed for competitive performance.

**Comment by vincenthz** [comment]
agreed. FYI it's completely not benchmarked yet, also readDouble could very likely go much faster with a more ad-hoc approach.

**Comment by ndmitchell** [comment]
FWIW, readDouble from Text was only 20% faster than the Foundation one - but that's a very bad benchmark that converts from `[Char]` in the loop.
