### ISSUE TITLE
Inaccuracies introduced by readDouble

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#243]
Given:

```haskell
print $ readDouble $ fromList "-31.548"
print $ (read "-31.548" :: Double)
```

I get:

```
Just (-31.548000000000002)
-31.548
```

The foundation read is slightly off.

**Comment by vincenthz** [comment]
This is very linked to the way it's built from integral + floating ("simpler" algorithm) instead of in one go (which is the optimised way I'm aluding to in the other ticket). `Data.Text.Read.double` has the same construction and give the same approximation.

**Comment by ndmitchell** [comment]
Ah, I didn't realise readDouble had basically identical issues. I guess I'm just spoilt by the standard `read/show` being so robust for `Double`.
