### ISSUE TITLE
fromBytes UTF8 gets stuck

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#25]
```
> print $ F.fromBytes F.UTF8 $ F.fromList [169,32,50,48,48,56,32,98,121,32,65,110,100,121,32,71,105]
("",[169,32,50,48,48,56,32,98,121,32,65,110,100,121,32,71,105])
```

Seems that it shouldn't just get wedged and ignore the rest of the bytes entirely.

**Comment by vincenthz** [comment]
The problem is that open a huge can of worms :)

The question is what to do with the offending sequences, ignore, warnings, errors, errors + way to skip

**Comment by ndmitchell** [comment]
I suggest the Encoding argument generalise to pick the behaviour. It seems the current behaviour is rarely the right one.

**Comment by ndmitchell** [comment]
Specifically here I have no way to know if decoding failed or if it's still waiting for more chars, without breaking the abstraction.

**Comment by ndmitchell** [comment]
Suggesting is to have many types of encoding, and change the type to:

   fromBytes :: Encoding -> UArray Word8 -> Either Error (String, UArray Word8)

In the above encoding by default it would return Left - failure to decode. We also want other encodings such as UTF16, UTF8_but_i_might_have_ansi etc.

**Comment by vincenthz** [comment]
there's now a fromUTF8Lenient function that insert replacement character where it's invalid. it's extremely inefficient algorithm (3 string concat per invalid sequence, lots of room for optimisation), but for mostly valid data it shouldn't be too noticeable right now.

**Comment by ndmitchell** [comment]
Any reason for not adding it as a separate encoding type?

**Comment by vincenthz** [comment]
yes, it's basically not an encoding, as in we can go String -> ByteArray with this encoding, and the return error is quite different (as in no error). I think it might move from:

```
fromBytesLeniens :: ByteArray -> (String, ByteArray)
```

to

```
fromBytesLenient :: Encoding -> ByteArray -> (String, ByteArray)
```

to allow for lenient UTF16 too

**Comment by ndmitchell** [comment]
It now works over the entire tarball, taking 8.86 seconds. The profile is:

```
break            Core.Array.Unboxed  46.0   70.3
fromBytesLenient Core.String.UTF8    20.8    4.1
validate.one     Core.String.UTF8    13.1    0.0
linesC.go        Main                 6.1   10.6
```

Removing String conversion, so no UTF8 routines, drops that to 6.467 seconds. Switching all the way to ByteString drops that to 4.909 seconds. Profiling the ByteString routines spending 60% in break, while with the no UTF8 version I get 77% in break (during profiling, which may not be representative of optimised, of course...).

It's good enough to move on to investigating the mmap stuff.
