### ISSUE TITLE
Add unchecked to UTF8 code

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#26]
Perhaps add a `Raw` data type to `Encoding` and `fromBytes Raw x = (String x, empty)`?

**Comment by ndmitchell** [comment]
Should be called `unsafeFromBytes` and just wrap around a String. Any operations on an incorrect UTF8 string may well crash at runtime, or do other nasty things (but not segfault).

**Comment by ndmitchell** [comment]
This is required for Hoogle mmap side.

**Comment by vincenthz** [comment]
I think `fromBytesUnsafe` should just work as envisioned but beware runtime issue. shouldn't segfault though.
