### ISSUE TITLE
Add upper/lower functions

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#261]
I'd have expected `upper, lower :: String -> String`. Doing the transformation via a mapping might be the best way, but sometimes that doesn't mean the same thing for String, and it's messy.

**Comment by vincenthz** [comment]
there's `charMap` (which is available through the InnerFunctor also) that take cares of all the messy details of string character transformation (Char -> Char) in utf8 encoding.

Now if you want unicode upper/lower, this method would get you 98% there. For the 2% remaining you'll have to remove the (Char -> Char) assumption, but the fill&realloc functions of charMap can be re-used.

**Comment by ndmitchell** [comment]
Would you accept a pull request simply adding these methods as sugar on top of `charMap`? They seem like a sensible inclusion in the library, and their implementation is almost a secondary concern.

**Comment by vincenthz** [comment]
yeah absolutely, add what is necessary. I'ld just like to add the limitation of the implementation in the comment (I suspect you're not going to go for 100% unicode implementation, which is very fiddly and annoying to do I expect.)

**Comment by ndmitchell** [comment]
Yep, that was my plan. Although I note Data.Text just has a big old list of characters which are "special": https://hackage.haskell.org/package/text-1.2.2.1/docs/src/Data-Text-Internal-Fusion-CaseMapping.html#upperMapping

**Comment by vincenthz** [comment]
Looks like it's automatically generated from some unicode stuff which sounds like the right things with the fickleness of the standard.

Maybe as a starting point just having an explicitely named "upperASCII" which only upper ascii character (if that's what you want) would be a good idea ? I don't have any strong feeling here, so I'm happy to defer to your good judgment.

**Comment by ndmitchell** [comment]
The `text` package converts http://unicode.org/Public/UNIDATA/CaseFolding.txt and http://unicode.org/Public/UNIDATA/SpecialCasing.txt into tables which it uses to drive conversion. Doing the full thing is a fair bit of work. Worth it in the long term, but I imagine few people care immediately, so have put in the interface with a bad (99.5% correct, dead slow) interface, to be improved later.
