### ISSUE TITLE
Improve the speed of UArray Word8 to ByteString

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#267]
Benchmarking a real application shows the conversion to ByteString to be a huge performance regression relative to pre-foundation. I wrote a little benchmark:

```haskell
{-# OPTIONS_GHC -O2 -Wall #-}
{-# LANGUAGE BangPatterns, OverloadedStrings #-}

import qualified Data.ByteString.Char8 as BS
import Criterion.Main
import Data.ByteString (ByteString)
import Data.ByteString.Internal (toForeignPtr, unsafeCreate, memcpy)
import qualified Foundation as F
import Foundation.Array
import Foundation.Array.Internal (withPtr, fromForeignPtr)

fromByteString :: ByteString -> F.UArray F.Word8
fromByteString = fromForeignPtr . toForeignPtr

toByteString :: F.UArray F.Word8 -> ByteString
toByteString v = unsafeCreate len $ \dst -> withPtr v $ \src -> memcpy dst src len
  where !len = F.length v

bs = "foundation is the future" :: BS.ByteString
str = fromByteString bs :: UArray F.Word8

main = defaultMain
  [ bench "BS.copy"  $ whnf BS.copy bs
  , bench "toByteString" $ whnf toByteString str
  ]
```

Here `toByteString` was copied out of foundation-edge. That gave:

```
benchmarking BS.copy
time                 31.15 ns   (30.99 ns .. 31.33 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 31.07 ns   (30.96 ns .. 31.22 ns)
std dev              443.0 ps   (348.1 ps .. 592.6 ps)
variance introduced by outliers: 17% (moderately inflated)

benchmarking toByteString
time                 120.8 ns   (118.2 ns .. 123.8 ns)
                     0.997 R²   (0.996 R² .. 0.999 R²)
mean                 122.3 ns   (120.8 ns .. 124.1 ns)
std dev              5.584 ns   (4.873 ns .. 6.747 ns)
variance introduced by outliers: 66% (severely inflated)
```

Aka that Foundation is 4x slower than ByteString. I then tried a bunch of things, but adding `{-# INLINE withPtr #-}` to foundation fixed it:

```
benchmarking BS.copy
time                 30.60 ns   (30.33 ns .. 30.94 ns)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 30.45 ns   (30.34 ns .. 30.67 ns)
std dev              533.9 ps   (311.7 ps .. 930.4 ps)
variance introduced by outliers: 24% (moderately inflated)

benchmarking toByteString
time                 30.37 ns   (30.29 ns .. 30.47 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 30.46 ns   (30.36 ns .. 30.55 ns)
std dev              340.7 ps   (286.4 ps .. 424.4 ps)
variance introduced by outliers: 11% (moderately inflated)
```

Looking at the core I suspect lack of specialisation was partly a factor and having to create a fresh IO closure.

That said, I note that `withPtr` has really 3 branches - ByteArray pinned, ByteArray unpinned and Ptr. Two of those are zero-copy, but one reallocates. What I'd really like is an `Internal` method of foundation with the signature:

```
copyToPtr :: (PrimMonad prim, PrimType ty) => UArray ty -> Ptr ty -> prim ()
```

That could do the memcpy for those which are pinned and for unpinned could poke things over directly avoiding an intermediate allocation. Writing `toByteString` on top of that would be nice and efficient.

**Comment by vincenthz** [comment]
thanks for the benchmarks.

yes indeed, we really need this; going through `withPtr` is definitely the less efficient thing that can be done, considering what it is for.

It should be just a matter of exposing the much more efficient (not benchmarked yet) `copyByteArrayToAddr#`

**Comment by ndmitchell** [comment]
Any thoughts around just shoving the `INLINE` pragma on `withPtr` for the moment? I'm not a fan of such pragmas in general, but given the significant impact to a real test case it seems justifiable - at least until the alternatives are available.

**Comment by vincenthz** [comment]
so `copyToPtr` is 3ns slower on my machine.

**Comment by vincenthz** [comment]
this is my current numbers, with also the case where you have a UVecBA

```
benchmarking toByteString-copyPtr
time                 32.41 ns   (32.26 ns .. 32.55 ns)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 32.41 ns   (32.32 ns .. 32.49 ns)
std dev              329.1 ps   (289.5 ps .. 441.9 ps)

benchmarking toByteString-withPtr
time                 41.27 ns   (38.63 ns .. 43.56 ns)
                     0.979 R²   (0.972 R² .. 0.988 R²)
mean                 38.20 ns   (36.41 ns .. 39.81 ns)
std dev              5.790 ns   (4.990 ns .. 7.003 ns)
variance introduced by outliers: 96% (severely inflated)

benchmarking toByteString-native-copyPtr
time                 31.82 ns   (30.66 ns .. 34.02 ns)
                     0.986 R²   (0.979 R² .. 0.994 R²)
mean                 34.71 ns   (33.74 ns .. 36.70 ns)
std dev              4.615 ns   (3.581 ns .. 6.710 ns)
variance introduced by outliers: 95% (severely inflated)

benchmarking toByteString-native-withPtr
time                 45.88 ns   (43.82 ns .. 48.54 ns)
                     0.986 R²   (0.981 R² .. 0.995 R²)
mean                 44.92 ns   (43.92 ns .. 46.84 ns)
std dev              4.294 ns   (3.190 ns .. 5.897 ns)
variance introduced by outliers: 90% (severely inflated)

benchmarking BS.copy
time                 30.87 ns   (29.00 ns .. 32.78 ns)
                     0.982 R²   (0.977 R² .. 0.991 R²)
mean                 30.00 ns   (29.05 ns .. 31.18 ns)
std dev              3.519 ns   (2.858 ns .. 4.258 ns)
variance introduced by outliers: 94% (severely inflated)
```

**Comment by vincenthz** [comment]
Also I'm suspicious that withPtr is currently safe with unpinned bytearray, since `bytearrayContent#` is called and no-one is actually holding onto the `ByteArray#`

**Comment by vincenthz** [comment]
Also as another data point, the new Block's `copyToPtr` is faster (by less than 1 ns) than BS.copy. so I'm tempted to think that the sum type of is responsible for the small overhead of ~2 to ~4ns compared to ByteString, and that we can't really be faster here (I've looked at the simpl and the asembly, there's not much operations going on apart from the sum type case as extra operation)

**Comment by ndmitchell** [comment]
If it had been in the 1-4ns range I doubt I'd have noticed it on the profile in the first place - that seems like an awesome result and a price well worth paying for the flexibility to avoid fragmentation on short strings and have fast C interop in a single type.

**Comment by vincenthz** [comment]
yes, I was just saying the same thing couple of minutes ago, I'm happy paying a couple of nanoseconds penalty for a much better type as the general API. (and for certain lowlevel optimisation we'll have Block too)
