### ISSUE TITLE
Add IsString FilePath

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#27]
It's very useful in practice, and currently people are just going to do:

```
F.filePathFromString $ F.fromString "C:/Neil/hs-foundation/examples/FieldTrip.txt"
```

Which isn't really safer, just less convenient. (I remain unconvinced about reinventing virtual file paths at the same time as doing the rest, but this lets me ignore that for the most part.)

**Comment by vincenthz** [comment]
think it's been fixed already
