### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#276]
With the copyPtr stuff now done I'd love to get a release.

**Comment by ndmitchell** [comment]
Any idea when the next release will be? If it's going to be a while I'll probably upgrade to a snapshot and mirror it locally for the time being (the performance benefits of `copyPtr` are huge in practice).

**Comment by vincenthz** [comment]
I think the answer was 2 days ago, but I got distracted with other thing, and the lack of automated (extended) CI.

**Comment by vincenthz** [comment]
released. I'ld really like to have a more automated system and more lightweight for making release, but look like that's not going to happens any time soon. as a workaround, I'm thinking releasing a `foundation-weekly` package maybe, although that come with annoying caveat of not scaling to a hierarchy of package.

**Comment by ndmitchell** [comment]
Thanks for the release. What's not lightweight about a release? I'd much rather have a real foundation release once a week rather than a separate foundation-weekly.

I have a tool `neil sdist` which does all the sanity checks and does everything apart from the actual upload. I then have a tool `neil tag` which generates git tags etc and signs everything. They aren't too complex and I can point you at them (or you are welcome to reuse them, if foundation adheres to me packaging standards).

**Comment by vincenthz** [comment]
As long as the equation needs me to be in it, it's never going to be lightweight like I'm imagining. My goal would be to get out of the way, so that every week travis could make a weekly release without my assistance (it already support a cron like feature that allow to express the periodic bit)

As a more elaborate "non-weekly" release, a more lightweight process would just involve this repository (for example tagging / github releasing), than having to deal with an external system which need separate access rights.

**Comment by vincenthz** [comment]
hm just tried `neil`, and this is a bit raw.

```
$ neil sdist
neil: Cabal check gave bad warnings:
"/bin/sh: cabal: command not found"
```

```
$ neil tag 
Confirm to tag the release with 'neil: src/Git.hs:63:9-75: Irrefutable pattern failed for pattern [name]
```

**Comment by ndmitchell** [comment]
I really want the feature that a release is simply doing a git tag - every other step is entirely pointless. Unfortunately, that's a long way around.

Note that `neil` is very raw - there's a reason I named it `neil` and not anything more useful. `neil sdist` requires cabal to be on the path - you should install `cabal` first.

`neil tag` requires your Cabal `version` field to be lowercase, which `neil check` actually checks. As I said, it's for packages which obey my undocumented, precise and constantly changing standards (I got sick of having a variety of casings in my .cabal files!)

**Comment by vincenthz** [comment]
I don't have `cabal` installed on purpose [1], is there a way to the same things with just `stack` ?

As to .cabal fields, I'm happy standardizing to lower case, as I too have a variety of casings for no good reason.

[1] that was specially crucial for me to be able to move to stack, to unlearn all the habits of doing things with cabal.

**Comment by ndmitchell** [comment]
No, I require `cabal` in the scripts. It could perhaps be ported to `stack`, but I worry too much about subtle edge cases. Perhaps just run this with `cabal` on the PATH? Anyway, I'll investigate tonight and see what it would take to fix all the `neil check` warnings (which is run before `neil sdist`).

**Comment by ndmitchell** [comment]
I've raised #283 to fix all the `neil check` invariants. However, there are lots of other `neil check` rules on things like the style of the README and the `.travis.yml` file that you probably don't want to obey. My guess is the `neil` tool might serve as inspiration for a solution, rather than an end solution, especially if you want to use `stack`. In fact, `neil sdist` should probably be moved to a single `stack` command and properly supported...
