### ISSUE TITLE
foundation 0.0.10 breaks memory-0.14.5

### ISSUE THREAD

**Issue by waldheinz** [haskell-foundation/foundation#295]
memory depends on `foundation >= 0.0.8`, so it currently pulls in foundation 0.0.10. But with that version, memory does not build:

```
[14 of 28] Compiling Data.Memory.Hash.SipHash ( Data/Memory/Hash/SipHash.hs, dist/build/Data/Memory/Hash/SipHash.o )
[15 of 28] Compiling Data.Memory.Hash.FNV ( Data/Memory/Hash/FNV.hs, dist/build/Data/Memory/Hash/FNV.o )
[16 of 28] Compiling Data.ByteArray.Types ( Data/ByteArray/Types.hs, dist/build/Data/ByteArray/Types.o )

Data/ByteArray/Types.hs:67:23: error:
    Not in scope: data constructor ‘F.Size’
    Neither ‘Foundation’, ‘Foundation.Array.Internal’, ‘Foundation.String’ nor ‘Foundation.Collection’ exports ‘Size’.
```

It seems the `Size` constructor was previously exposed but was dropped with foundation 0.0.10. That constructor was exposed up to version 0.0.9.

**Comment by NicolasDP** [comment]
Thanks for the issue. It seems this is a [memory](https://github.com/vincenthz/hs-memory) issue so I created an issue in this module referencing your bug report.

**Comment by waldheinz** [comment]
I didn't know if foundation adheres to the semantic versioning rules, but event if it did (and 0.0.10 would instead have been 1.0.0) memory would break anyway (as it does not specify an upper bound). So I guess fixing memory is the right thing to do. Thanks!

**Comment by NicolasDP** [comment]
not yet. Semantic versioning is something we are still discussing but unfortunately (or fortunately) foundation may still change APIs from time to time as we are always trying to bring the best of modern Haskell to our APIs.

I talked with @vincenthz about the issue and we will try to address it as soon as possible.
