### ISSUE TITLE
all & any is implemented through a list

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#300]
Implementation of maximum & minimum is not optimal at all and used a list for most types:

```haskell
instance Collection (BA.Array ty) where
    ...
    all p = Data.List.all p . toList
    any p = Data.List.any p . toList
     ...
```

types having a bad implementation:

* [ ] Block
* [ ] UArray
* [ ] Array
* [ ] String
* [ ] Bitmap
* [ ] ChunkedUArray

**Comment by ThreeFx** [comment]
I'm gonna take a look at this.
