### ISSUE TITLE
Support mmap for string/array

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#31]
I can call Core.Foreign.fileMapRead, to get a FinalPtr Word8, but I really want an `UArray Word8`. Why not just have `fileMapRead` return that directly?

**Comment by vincenthz** [comment]
agreed; in this case it's due to having implemented the mmap capability before having the Addr capability in the `UArray`

**Comment by vincenthz** [comment]
fixed by 5a98635
