### ISSUE TITLE
`fromBytes` throws exceptions instead of returning the error inside the `Maybe ValidationFailure`

### ISSUE THREAD

**Issue by jship** [haskell-foundation/foundation#312]
The following program throws a `ByteOutOfBound` exception instead of providing the error in the `Maybe ValidationError` in the triple returned by `fromBytes`.

```haskell
#!/usr/bin/env stack
-- stack script --resolver lts-8.17 --package foundation
{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Control.Monad
import Foundation
import Foundation.String
import Foundation.String.ASCII
import Foreign.C.Types

printString :: Encoding -> UArray Word8 -> IO ()
printString enc bytes = do
  -- fromBytes :: Encoding -> UArray Word8 -> (String, Maybe ValidationFailure, UArray Word8)
  let (string, minvalid, rest) = fromBytes enc bytes
  putStrLn string
  case minvalid of
    Nothing -> putStrLn "Valid!"
    (Just vf) -> putStrLn "Invalid!"
  when (null rest) $ do
    putStrLn "rest is empty"
  unless (null rest) $ do
    putStrLn "rest is not empty"

main = printString ASCII7 (fromList [0xff])
```

```shell
strings: ByteOutOfBound 255
```

**Comment by NicolasDP** [comment]
@jship, is it a bug you are happy to look at ?

**Comment by jship** [comment]
Yes, will take a look at it.

**Comment by jship** [comment]
@NicolasDP: Can think of a few options to this and would like to discuss with you.

1. Do something similar to what `UTF8` does with its `validate` function.  UTF8 doesn't use the fromEncodeBytes machinery.
2. Update `Builder` itself to wrap an error transformer.
3. Update `builderBuild` to no longer discard the monadic result and return possible error there.

Interested in pairing on this today with myself and @Tiltman?

**Comment by NicolasDP** [comment]
I think you are looking at the right solution. We could try some stuff with the [Builder](https://github.com/haskell-foundation/foundation/blob/master/Foundation/Boot/Builder.hs)

We can extend it with `MonadThrow` and `MonadCatch`. This will allow us to do some error handling/reporting in `convertFromTo` and the `Encoding .encodingWrite` specialised function.
