### ISSUE TITLE
Why do we need `foldl` ?

### ISSUE THREAD

**Issue by tekul** [haskell-foundation/foundation#319]
For example, `Block` includes both `foldl` and `foldl'`.

**Comment by ndmitchell** [comment]
Kill `foldl`, leave `foldl'`.

**Comment by ThreeFx** [comment]
Should `foldl'` be renamed in this case? Both ways I see a problem: Either beginners are confused why `foldl'` only comes with an apostrophe and otherwise removing the apostrophe removes the subtle hint that it's a strict fold.

**Comment by ndmitchell** [comment]
Most beginners who know about `foldl` will probably read articles that it's terrible and should never be used. As a result, they'd be incorrectly scared of the Foundation one.
