### ISSUE TITLE
FilePath API

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#35]
* [ ] extension manipulation
* [x] path dropping / append filename
* [ ] parent
* [ ] windows support
* [ ] OS support (`readdir`)

**Comment by vincenthz** [comment]
linked with #27

**Comment by NicolasDP** [comment]
Hi Vincent, if you don't mind I'll start working on this.

**Comment by NicolasDP** [comment]
I'm thinking to keep what you already have done in the VFS (but in another module dedicated to Path).
