### ISSUE TITLE
Add spanEnd, breakEnd

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#384]
Functions like span/break but that work from the end of the array/string. Also useful to have dropWhileEnd, takeWhileEnd etc. Would make Weeder able to use more of foundation for parsing (currently it just converts to list and then does it on `[Char]`)

**Comment by vincenthz** [comment]
I've started to add support for the basic end method, but I don't have to push it through the finish line before end of the month; In the meantime, testing and possibly adding the other functions would go a long way.
