### ISSUE TITLE
Reduce duplication

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#389]
Things like `filter` in `UArray/BA.hs` and `UArray/Addr.hs` are perfect copies. Of course, once you fix a bug in one of them, they'll stop being perfect copies and change to being wrong... Have you considered some technique to eliminate the duplication - CPP `#include` springs to mind.

**Comment by vincenthz** [comment]
I definitely considered some stuff, but truthfully they all suck in their respective way as much or more as copying code from BA to Addr manually with a diff tool.
