### ISSUE TITLE
Doesn't currently build against musl

### ISSUE THREAD

**Issue by purcell** [haskell-foundation/foundation#393]
Musl - a popular safer `libc` variant used by Alpine Linux and others - has `types.h`, but not `linux/types.h`, so builds of Foundation fail on musl-based systems like Alpine. Would be great to be able to build Foundation there too, especially since Alpine has GHC 8 now, and Stack compiles there happily. Unsure whether the same applies to `linux/random.h`.

**Comment by vincenthz** [comment]
I agree there's no reason to prevent building on musl, but I personally have limited capacity to install alternatives environment for building/testing. so unless someone (you ?) want to fix this issue, which shouldn't be too hard after finding the right include/#ifndef incantations.

**Comment by purcell** [comment]
Cool, I can probably look at that. The Travis build doesn't currently allow for testing compilation against different `libc`s, but I guess that's not a big deal as long as any changes I submit at least don't break the regular build. :-)
