### ISSUE TITLE
Stop using byteArrayContents# directly

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#399]
Following #397, I read through the code base looking for `byteArrayContents#`. It's used incorrectly every time. I recommend defining `withByteArrayPtr :: ByteArray# -> (Ptr a -> IO b) -> IO b` or similar to capture the correct pattern with the required `touch`. In particular:

https://github.com/haskell-foundation/foundation/blob/dc8d4f7c1ffb34878781c845387835ca7edb4443/basement/Basement/UArray/Mutable.hs#L127

This looks like another instance of #397, almost verbatim.

https://github.com/haskell-foundation/foundation/blob/dc8d4f7c1ffb34878781c845387835ca7edb4443/basement/Basement/Block/Mutable.hs#L87-L88

This defines a function `mutableGetAddr` which is just as unsafe as `byteArrayContents#` which is then used unsafely in StopWatch. In particular I loved:

https://github.com/haskell-foundation/foundation/blob/dc8d4f7c1ffb34878781c845387835ca7edb4443/Foundation/Time/StopWatch.hs#L55-L61

The touch is there, just as a comment...

**Comment by vincenthz** [comment]
I think it has been addressed now

**Comment by ndmitchell** [comment]
I disagree! I think that where a function has a requirement for a magical touch later on should be defined as `with*` functions and used exclusively that way. Looking at the current foundation functions, I think:

* There should be exactly one use of `byteArrayContents#` in the foundation library, which writes the `with` function.
* `mutableGetAddr` shouldn't exist, as it's another function based on `byteArrayContents#` that requires the magical touch.
* StopWatch should stop using a lot of these dangerous functions, as it's lots of CPP, and I'd be quite surprised if all possible CPP branches were correct.
* My approach would be to have `Basement.UArray.Base` expose `withPtr` variants and not touch or unpack things, so they were always used correctly.

I think it's important to get the primitives correct by construction where possible, since when it goes wrong (and you get arbitrary memory corruption) the consequences and debugging experience both leave a lot to be desired...

**Comment by ndmitchell** [comment]
If you agree with the plan, but don't want to implement it, I'd consider making the changes myself.

**Comment by vincenthz** [comment]
I'm fine changing things in `initPrecise` and `stopPrecise`, since they don't have any timing impact. however `startPrecise` is tailored to not do anything superfluous for timing reason, and numbers seems to indicate the resolution of `StopWatch` right now is actually a bit better than criterion's one (back when I introduced the StopWatch, I haven't used it since)

note that there's 2 ways to keep things alive, touch being the first one; startPrecise is using the second method.

**Comment by vincenthz** [comment]
alternative would be to remove all usage of `Block` in `StopWatch` with an unknown construct that allow to pass 2 Word64 back&forth without allocating a ByteArray# (only for windows and linux, as OSX is more friendly with just a single Word64)

**Comment by vincenthz** [comment]
no, with the RealWorld#, everything is sequenced without the ability to be re-ordered, the last wrapping of blk will be equivalent to a touch.

I had a detail look in detail at `MO_touch`, it's definitely a no-op at the asm level. it doesn't necessary have no impact over all the stages of core/cmm/etc, although in those specific simple cases, it shouldn't matter, so let's move everything to withPtr.

**Comment by ndmitchell** [comment]
The wrapping doesn't happen inside IO. To prove that, I wrote `onlyStart = startPrecise >> return ()` and compiled it. I got the Core:

```
Foundation.Time.StopWatch.onlyStart1
  = \ (s_iepP :: GHC.Prim.State# GHC.Prim.RealWorld) ->
      case GHC.Prim.newAlignedPinnedByteArray# 16# 8# s_iepP of
      { (# ipv_ieuK, ipv1_ieuL #) ->
      case GHC.Prim.unsafeFreezeByteArray# ipv1_ieuL ipv_ieuK of
      { (# ipv2_iekz, ipv3_iekA #) ->
      case {__pkg_ccall_GC Win32-2.3.1.1 Addr#
                              -> State# RealWorld -> (# State# RealWorld, Int# #)}_aekG
             (GHC.Prim.plusAddr# (GHC.Prim.byteArrayContents# ipv3_iekA) 8#)
             ipv2_iekz
      of
      { (# ds4_aekL, ds5_aekM #) ->
      (# ds4_aekL, GHC.Tuple.() #)
      }
      }
      }
```

There's absolutely nothing hanging on to the buffer at the point it gets passed to a foreign call. Even if there was, the subtleness of the argument means I'd still recommend using a with pattern instead, which I think will have zero impact on the code at the end.

**Comment by vincenthz** [comment]
Thanks. always good to clear misconception, and had an epiphany about why that it happening which lie in the same `s` for `IO $ \s -> (# a, s #)`.

Also to re-iterate what was above, I'm fine moving to withPtr already since we cleared the performance impact of `touch#` (and now the second reason)

**Comment by ndmitchell** [comment]
I raised PR #417 with all the changes in.
