### ISSUE TITLE
IOError should not be in the Prelude

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#4]
It's a big module of stuff you rarely want. Having it in the Prelude seems weird.

**Comment by vincenthz** [comment]
maybe useful to catch IOError ?

**Comment by ndmitchell** [comment]
I find that to be rarely useful, but if you did, surely exporting `IOError` is sufficient? The `IO.Error` module is pretty large, and of limited utility, so having all those symbols "in scope" by default seems the wrong default.

**Comment by vincenthz** [comment]
fixed. definitely shouldn't be exported by default
