### ISSUE TITLE
Question: error handling and callstacks

### ISSUE THREAD

**Issue by flip111** [haskell-foundation/foundation#448]
Is anything special being done to improve error handling and error reporting in the functions. I was watching this video and all the errors that can occur look very scary https://youtu.be/7NB8tMa8sUk?t=30m27s

**Comment by vincenthz** [comment]
many things are beyond foundation's control, but we try to have better functions that either need less error handling (by using better types) and we have a callstack abstractions that compile on more versions than base, so it's easier to roll it on basic stuff.

**Comment by flip111** [comment]
On 35:18 in that video there is an error `*** Exception: openFile: does not exist (No such file or directory)` without actually telling which file (filepath passed) and which line in the code. I see foundation delegate openFile to System.IO https://github.com/haskell-foundation/foundation/blob/08dd88a98ed1eb793e01423aee6f898da9defe3c/Foundation/IO/File.hs#L43-L45 Can something be done here to improve this error?

> we have a callstack abstractions that compile on more versions than base

I don't understand what you mean, could you elaborate please?

**Comment by vincenthz** [comment]
until we replace the IO system (which is in foundation's plan for some day), I don't think this will get fixed.

The Callstack abstraction is easier to use in foundation and don't required annoying ifdef; so we could benefit with wider usage in many more places than legacy base packages:
https://github.com/haskell-foundation/foundation/blob/master/basement/Basement/Compat/CallStack.hs

**Comment by flip111** [comment]
What about adding `HasCallStack` to `openFile` wouldn't that help improve the error reporting?

**Comment by vincenthz** [comment]
Quite possible and that sounds like a good idea (I never mixed callstack and IO exceptions, I'm curious how they work in practice), could you test and submit a patch ?

**Comment by flip111** [comment]
Great, i'll look into it. I'll be adding `HasCallstack` to all the functions in `Foundation.IO.File`. Are there any other places that would benefit from having `HasCallstack` ?

**Comment by vincenthz** [comment]
Possibly. I would try small first and see what the experiment gives you, and we can roll further places in the future. It's easier to review and merge when it's a smaller thing

**Comment by flip111** [comment]
Okay i gave it a shot. This is my code

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Foundation
import GHC.Stack (HasCallStack, callStack, prettyCallStack)
import Foundation.IO (openFile, IOMode(ReadMode))
import GHC.IO.Handle (Handle)
import GHC.IO.Exception
import Control.Exception

main :: IO ()
main = do
  ex <- try otherIO
  case ex of
    Left (e :: IOException) -> errorWithCallStack $ show e
    Right _ -> putStrLn "hello world"

otherIO :: HasCallStack => IO ()
otherIO = someIO

someIO :: HasCallStack => IO ()
someIO = ioError $ IOError Nothing IllegalOperation "a" "b" Nothing Nothing

-- openFileIO :: HasCallStack => IO Handle
-- openFileIO = openFile "yada yada" ReadMode

errorWithCallStack :: HasCallStack => String -> a
errorWithCallStack msg = error (msg <> "\n" <> (fromString $ prettyCallStack callStack))
```

This is the output
```
exceptionf: a: illegal operation (b)
CallStack (from HasCallStack):
  errorWithCallStack, called at src/Main.hs:16:32 in main:Main
```
So it's missing line 20 and 23 in the trace which is not good. The following issues might be blocking this from working correctly:

https://github.com/haskell-foundation/foundation/issues/454
https://ghc.haskell.org/trac/ghc/ticket/12096
https://ghc.haskell.org/trac/ghc/ticket/14634

And related confusion about how `errorWithCallStack` is supposed to work https://ghc.haskell.org/trac/ghc/ticket/14635#ticket
