### ISSUE TITLE
No simple way to convert String to FilePath

### ISSUE THREAD

**Issue by ghost** [haskell-foundation/foundation#449]
When getting arguments as strings from command line there is no function to convert it to a filepath so it can be used to open files. This case is very common, thus should be made easy to do.

**Comment by NicolasDP** [comment]
I agree, it is missing. Would be nice to have a proper function to convert from a `String` and from a `LString`.

In the mean while, `FilePath` is an instance of `IsString` so you can use `fromString` but an error will throw an exception `ContiguousPathSeparator` (which is unfortunately not exported).
