### ISSUE TITLE
readFile in basement?

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#459]
@vincenthz suggested I flip `weeder` to `basement`. The one problem with that is the function I defined:

```haskell
readFileUTF8 :: FilePath -> IO Str
readFileUTF8 = fmap (fst3 . S.fromBytes S.UTF8) . S.readFile . S.fromString
```

Unfortunately `readFile` returning `UArray Word8` isn't available from `basement`. Should it be? If not, I'll stick to `foundation`.

**Comment by vincenthz** [comment]
It's not currently available outside `foundation` for now, however one unexecuted plan is to move all lowlevel system bindings which probably include `readFile` to an "operating system dependent stuff" package sitting between basement and foundation.
