### ISSUE TITLE
Missing MonadFix instance for StateT

### ISSUE THREAD

**Issue by pavolzetor** [haskell-foundation/foundation#483]
Some libraries rely on `mdo` (such as llvm IRBuilder) and are unusable when using foundation. Could you please add MonadFix instances?

**Comment by cocreature** [comment]
`ReaderT` and `ExceptT` also don’t have `MonadFix` instances atm, not sure if `foundation` defines other monad transformers.

**Comment by NicolasDP** [comment]
Thanks @cocreature . I've added the `MonadFix` instances for `ReaderT` and `ExceptT` in #484
