### ISSUE TITLE
Define whether portability and GHCJS is a goal or not.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-foundation/foundation#486]
I think it's not, but it isn't documented.

**Comment by vincenthz** [comment]
it's not indeed. it's documented indirectly in https://github.com/vincenthz/haskell-pkg-guidelines/blob/master/support.md which in the README

**Comment by matthewbauer** [comment]
Could this be made explicit? I hit this trying to build a package for ghcjs that depends indirectly on "memory" which depends on this. This ticket was the first indication I found that ghcjs was not supported. Usually maintainers will accept patches that fix issues with ghcjs, but this looks like it won't be accepted in this case?
