### ISSUE TITLE
Some thoughts on foundation

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-foundation/foundation#492]
In general I'm a fan of radical rewrites of `base`, `Prelude`, etc. Nothing has clearly "won" yet, so experimentation is welcome and will hopefully benefit us all in the end.

I've seen `foundation` pulled into my packages more and more recently, probably due to `memory`'s dependency on it. At the moment it has [10 reverse dependencies](https://packdeps.haskellers.com/reverse/foundation), but `memory` has [101!](https://packdeps.haskellers.com/reverse/memory) - and it keeps going from there.

So here are my miscellaneous thoughts:

**1. New functionality is welcome**

- [`Foundation.Array`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Array.html)
- [`Foundation.Strict`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Strict.html)
- [`Foundation.String`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-String.html)
- [`Foundation.System.Entropy`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-System-Entropy.html)
- [`Foundation.Time.Bindings`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Time-Bindings.html)
- [`Foundation.Time.StopWatch`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Time-StopWatch.html)
- [`Foundation.Timing`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Timing.html)
- [`Foundation.Tuple.Nth`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Tuple-Nth.html)

I like seeing new functionality provided. I'm sure it's all benefiting someone, somewhere, but I'm especially impressed by `String`. I'd love to see this type pulled out into its own package.

**2. Re-exporting the good parts of `base` is standard**

- [`Foundation.Bits`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Bits.html)
- [`Foundation.Class.Bifunctor`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Class-Bifunctor.html)
- [`Foundation.Exception`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Exception.html)
- [`Foundation.IO`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-IO.html)
- [`Foundation.System.Info`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-System-Info.html)

Standard `base`-reimplementation stuff. Re-export the good stuff, improving a few type signatures along the way. I don't see _all_ of `base`'s good stuff re-exported here, so I'm a bit confused by the overall scope of the project. But hey, why not.

**3. Mini-reimplementations of "essentials" is okay**

- [`Foundation.Check`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Check.html)
- [`Foundation.Parser`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Parser.html)

These two modules (and an upcoming `Foundation.Test` module that I noticed) seem okay. It'd nice to have a mini-QuickCheck or mini-Parsec right in a base-like package, so long as they are sufficiently powerful. I do use `Text.ParserCombinators.ReadP` from time to time when I don't want to incur a dependency.

**4. Mini-reimplementations of "non-essentials" will lead to bloat**

- [`Foundation.Format.CSV`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Format-CSV.html)
- [`Foundation.UUID`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-UUID.html)
- [`Foundation.VFS`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-VFS.html)

These data types are starting to feel pretty fringe to me, and we already have dedicated, well known-packages available that solve these problems. It'd be helpful to know exactly what `foundation`'s scope is.

**4. Competing with community data types seems like a bad idea**

- [`Foundation.Conduit`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Conduit.html)
- [`Foundation.List.DList`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-List-DList.html)
- [`Foundation.Monad.Except`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Monad-Except.html)
- [`Foundation.Monad.Reader`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Monad-Reader.html)
- [`Foundation.Monad.State`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Monad-State.html)

On one hand, it's nice to have some of this functionality available immediately without having to reach for another package. I'd definitely be in favor of `foundation` re-exporting these type from `conduit`, `mtl`, etc.

However, _re-implementing_ them here is questionable. These types often appear in library code on Hackage. We should all be building our stuff on top of _the_ `Conduit` type, _the_ `DList` type, etc. since there is no convenient interop between them whatsoever.

**5. Competing with community type classes is a bad idea**

- [`Foundation.Class.Storable`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Class-Storable.html)
- [`Foundation.Collection`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Collection.html)
- [`Foundation.Hashing`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Hashing.html)
- [`Foundation.Math.Trigonometry`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Math-Trigonometry.html)
- [`Foundation.Monad`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Monad.html)
- [`Foundation.Numerical`](https://hackage.haskell.org/package/foundation-0.0.20/docs/Foundation-Numerical.html)

These are re-imaginations of what Haskell might have been. But the problem is, it's not what Haskell is. Type classes in particular, much more than data types, really do need community buy-in to be successful. 

That's not to say these ideas are bad! But the case for, say, improving `Hashable` should be made at the `hashable` package that we are all already using.

---

Overall, I'm afraid I'm not a fan of where `foundation` is currently going. I have two concrete suggestions.

Either:

- Drastically reduce the scope of `foundation` to just the new, awesome functionality, and `base` re-exports.

Or:

- Continue to radically re-imagine what Haskell might look like - but be clear that it's not meant to be depended upon in library code, as it contributes to further fragmenting our ecosystem, since we have not yet reached consensus on many of these ideas. In this case, `memory` should drop its `foundation` dependency.

So, there's my feedback. I realize this isn't a proper ticket, just random thoughts from a random Haskeller, please feel free to close whenever :)

Thanks for all your hard work!

**Comment by ndmitchell** [comment]
I thoroughly agree with everything @mitchellwrosen has said. I think depending on things like `NFData` would make foundation much easier to use - the mantra of trimming dependencies has become the principle behind foundation, and I don't think it's scalable in the long run.

**Comment by vincenthz** [comment]
Let's compare bloat shall we; text+vector vs basement+foundation

compilation time (3 runs avg):

```
text 45s
vector 60s
basement 30s
foundation 30s
```

so `1m45` vs `1m`

library size (.a | .so):
```
text 4.1M | 2.7M
vector 6.4M | 3.9M
basement 4.9M | 3.0M
foundation 5.3M | 3.2M
```
so `10.5M | 6.6M` vs `10.2M | 6.2M`

number talks, as usual ...

If you're happy with ill defined type class (Num), or bad API that require `undefined` (Storable), or bloat, or endless dependencies .. then use them. I'm not forcing anyone to use any of this, or any of my other libraries for that matter. please fork away if you're unhappy with any of this.
