### ISSUE TITLE
Lookahead in parser

### ISSUE THREAD

**Issue by klacansky** [haskell-foundation/foundation#496]
Hello, it is unclear to me how to write LL(1) parser using only functions from `Foundation.Parser`.
What I need is a function that let's me either get a character without moving forward or run a parser and get its result without moving forward.

**Comment by NicolasDP** [comment]
In the module `Foundation.Parser` there is a function `peek` to do what you are talking about. It is not yet in a released package. If you are using `stack` you can set the git repo as source for the package until the next release.
