### ISSUE TITLE
linker problem while installing basement from cabal

### ISSUE THREAD

**Issue by FlogFr** [haskell-foundation/foundation#509]
Hello,

I can't succeed to install basement with the command: `cabal install basement`.
This results in the linker error:
> /usr/bin/ld.gold: fatal error: -pie and -r are incompatible

I can install other libraries though.

Information on my system:
```
$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.3
```

**Comment by vincenthz** [comment]
Hi @FlogFr, this has nothing to do with basement. your linker (gold) failed with errors linked to how it's been used. likely some global options specified somewhere are getting used when linking.
