### ISSUE TITLE
Add builder for strings and boxed arrays

### ISSUE THREAD

**Issue by JanGe** [haskell-foundation/foundation#57]
It would be nice to also have builders for strings and boxed arrays like the one for unboxed arrays. That would make it much easier to start building your destination collection while going over an input collection if you can't know the length of the destination collection.
Maybe even a `Buildable` type class?

**Comment by vincenthz** [comment]
yes, this is a good idea. I envisioned having one array builder for the Boxed Array, but a class for it is very likely even better
