### ISSUE TITLE
arch should be an enum

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#59]
What are typical values for arch? That's the obvious question when looking at the function.

**Comment by NicolasDP** [comment]
This is a fair question. I guess it might be possible to dig into `base` to find the answer and document it.

**Comment by ndmitchell** [comment]
For info, on Windows, i get `i386`.

**Comment by NicolasDP** [comment]
I looked into base, I believe the potential results are: i386, x86_64, powerpc, sparc, arm...

https://github.com/ghc/ghc/blob/ffe4660510a7ba4adce846f316db455ccd91142a/mk/config.mk.in#L202-L203

**Comment by ndmitchell** [comment]
I wonder if this should be an enum, much like OS?

**Comment by vincenthz** [comment]
I would prefer as an enum too (eventually)
