### ISSUE TITLE
add fileMapReadWith

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#60]
Something like:

    fileMapReadWith :: FilePath -> (UArray Word8 -> IO a) -> IO a

**Comment by vincenthz** [comment]
I've added it, but not sure of the semantic. for example whether this should explicitely munmap at the end (potentially segfault lurking if someone is still holding on to the `ForeignPtr`), or do nothing which render the function a bit pointless (using `callback` instead of `return`

**Comment by ndmitchell** [comment]
It should happily segfault if someone is still holding on to the ForeignPtr - the alternative behaviour is of no use - you might as well just call `fileMapRead`.

**Comment by vincenthz** [comment]
done as part of #64
