### ISSUE TITLE
foldTextFile is undocumented

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#61]
What does it do? Is each thing a line? Or is each thing a fixed size? Or no guarantees? Any blanks?

What I really want is to push the String values into a conduit, which requires a different API anyway...

**Comment by vincenthz** [comment]
it's somewhat an experiment trying to just optimally get chunk one by one,  and pass it to a callback function as a unvalidated `String`. I'm not sure that's useful for anything.

About the conduit side of thing, wouldn't hGet will let you do what you want ?

**Comment by ndmitchell** [comment]
Yep, hGet looks what I want. Although I would like an explanation of what happens if there is an EOF, not enough bytes left etc.

**Comment by ndmitchell** [comment]
I'd probably delete `foldTextFile` as well, but entirely your call...

**Comment by vincenthz** [comment]
it's still there and documented for now, but it will likely disappear. Just searching in the design space for non-lazy IO stuff
