### ISSUE TITLE
Move mmap stuff to Core.IO

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#64]
I'd move the mmap stuff to it (in my mind, mmap is about IO, not foreign).

I'd also move the Core.String.IO to it, since its only 2 functions.

**Comment by ndmitchell** [comment]
#14 covers the String.IO piece, so leaving this for mmap.

**Comment by vincenthz** [comment]
I'm not keen on Core.IO. maybe Core.IO.Foreign would be a compromise that make sense ?

**Comment by ndmitchell** [comment]
I don't see any sense in which `mmap` is `Foreign`. I appreciate it has slightly dodgy guarantees, and pure values can change under weird circumstances, but that doesn't yell `Foreign` to me. Perhaps `Core.Mmap` is the right place for it? It does stand alone because of the weird purity issues.

**Comment by vincenthz** [comment]
Ok, what about `Foundation.IO.FileMap` ?

**Comment by ndmitchell** [comment]
Sure. And then you can put the general file map warnings at the top.

**Comment by vincenthz** [comment]
All done, the proper `with` function and the module move to `Foundation.IO.FileMap`. I need to see how to put some kind of test in place for this functionality too. Also probably need to wait on appveyor to tell me that I haven't broken the windows build doing blind changes in Windows.hs
