### ISSUE TITLE
Add Array conversion

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#65]
e.g. Array Word8 to Array Word32, which is essential to use data from an mmap.

**Comment by vincenthz** [comment]
it's subtly hidden under `unsafeRecast`. just need to find a suitable name and export this.
Generally not sure how to convert thing into another thing. `Convertible` might be the most generic candidate

**Comment by ndmitchell** [comment]
Great, just `unsafeRecast` is perfect. Not sure `Convertible` makes sense here - it's explicitly not doing a conversion, just an unsafe cast.

**Comment by vincenthz** [comment]
There's `recast` in `Foundation.Array.Internal`. This will likely move when we have a good story for converting things, but to be able to move forward let's put it there
