### ISSUE TITLE
String to Array Byte function

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#7]
Safe in one direction, unsafe in the other, but still handy.

**Comment by ndmitchell** [comment]
See also #26 and #25, so this function is just for `String -> ByteArray`.

**Comment by NicolasDP** [comment]
don't we want a class `ToByteArray` which could then be used by other types as well?

**Comment by ndmitchell** [comment]
Which other types?

**Comment by ndmitchell** [comment]
And it probably wants to be called something like stringToUTF8ByteArray or similar (at least mentioning the encoding in the name).

**Comment by NicolasDP** [comment]
sorry, I meant that, String is defined as an underlying type which is the ByteArray.
Some other types are defined like this as well. They are ByteArray (I'm thinking of FilePath or FileName). Which toByteArray would make sense as well.

**Comment by ndmitchell** [comment]
True - still not sure I'd make it a typeclass though, because FilePath and FileName and String all work very differently. If you handle their ByteArray conversion generically you will get very burnt.

**Comment by NicolasDP** [comment]
hmm... I see. not as easy I would have thought.

**Comment by vincenthz** [comment]
I think `toBytes UTF8` fits the bill
