### ISSUE TITLE
Rename Core to Foundation

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#70]
Having a library called foundation which provides stuff called Core is a bit weird. Perhaps rename the module prefix? I don't think those extra letters will matter to most people :)

**Comment by vincenthz** [comment]
I know where it's gonna swing since but maybe a vote as setting a precedent for this kind of thing would be a good idea. please use the +1 and -1 reaction (the button next to the edit post)  to the following motion

**Comment by vincenthz** [comment]
For changing the Core. hierarchy into a Foundation. hierarchy

**Comment by vincenthz** [comment]
pinging @NicolasDP @JanGe @tekul for voting above too

**Comment by JanGe** [comment]
What is the goal for the base `Core`/`Foundation` module? Will it export basically everything so I only need one import as an end user or will I have to import `Core.Number`, `Core.Collection`, etc. independently? With a lot of manual imports, I could see the need for short module names. 

But anyway, as there is auto completion and basic support for auto importing in some editors, I don't think the short module name is worth the inconsistence.

**Comment by tekul** [comment]
Definitely makes sense to me. Matching the project name is unambiguous.

**Comment by vincenthz** [comment]
Thanks all for participating in the first vote :)

Clearly unambigious result of 5 to 0 in favor of renaming.

I'll make sure to have pulled/merged/etc as many things as possible before renaming but it will happen today. let me know if you want to delay the renaming.

@JanGe: I'm not completely sure on it's going to work yet, but my goals is to keep the number of imports relatively low and provide by default a rich set of things; This is a pain point to have to imports tenth of modules every time you want to do anything modern (i.e. the triumvirate `text`, `bytestring`, `vector`, + other relatively common stuff).

**Comment by vincenthz** [comment]
this is now renamed
