### ISSUE TITLE
Add lines/unlines words/unwords

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#74]
Useful String functions that should be available.

**Comment by vincenthz** [comment]
there's mostly just splitOn with the element you want

**Comment by ndmitchell** [comment]
Mostly - but words omits blank elements, lines omits a final blank etc - lots of corner cases.

**Comment by vincenthz** [comment]
I've added dumb one that call the Prelude.String ones to make for the functionality; I really want to make a release
