### ISSUE TITLE
Redundant constraint?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-foundation/foundation#76]
Can you explain what the `c` is doing here?  It seems redundant.

````haskell
default imap :: (Functor f, Element (f a) ~ a, f a ~ c) => (a -> a) -> f a -> f a
````

**Comment by vincenthz** [comment]
It's tying the typical functor construction `f a` with the monomorphic collection `c` which is what the class use:

```
class InnerFunctor c where
```

**Comment by vincenthz** [comment]
Also I don't think it's redundant. GHC is not too happy if it is removed basically saying it doesn't know how to tie `c` in this function. Curious how do you get to this. Is this something that came up with a different compiler version ? or just while reading the code ?

**Comment by tomjaguarpaw** [comment]
Oh, it's fine.  It's just me trying to read code too early in the morning, sorry!

**Comment by vincenthz** [comment]
no worries Tom, hope you're doing well otherwise !
