### ISSUE TITLE
Double and Float operators support

### ISSUE THREAD

**Issue by vincenthz** [haskell-foundation/foundation#79]
Add Double and Float support in Core.Number

**Comment by vincenthz** [comment]
done for `+` `-` and `*`, but need to think about division. `Divisible` is only working with non fractional stuff

**Comment by vincenthz** [comment]
Sorry @JanGe I completely missed this

**Comment by vincenthz** [comment]
not sure `precision` make sense for Float and Double, the precision is fixed but vary on the exponant

**Comment by JanGe** [comment]
No worries :)
It was just a thought about the difference between decimal/integral and floating point types and I wasn't sure if if it would add any real value to have this. Also "Precision" was definitely the wrong word for what I meant.

I really like your approach with the rounding/truncating type class for conversion. Makes everything very explicit.

**Comment by vincenthz** [comment]
Thanks @JanGe
