### ISSUE TITLE
Consider splitting into separate packages

### ISSUE THREAD

**Issue by sgraf812** [haskell-foundation/foundation#80]
E.g. some people including me would love to see `foundation-array` and `foundation-string`, split up from the rest.

You could still have the `foundation` package re-exporting stuff in a suitable manner.

**Comment by ndmitchell** [comment]
Keeping the array and string together is very important, even if they do get split from the rest.

**Comment by vincenthz** [comment]
From my side of things, it's extremely unlikely that I would split `array` and `string` into their own packages. Maybe a collection of all types as `foundation-types` in the future, but it's a bit early to take this decision and have to deal with packages pain etc.

**Comment by vincenthz** [comment]
Also, @sgraf812 this query lack complete motivation on why it would be a good idea to do that. it somehow assume it is the right thing to do

**Comment by sgraf812** [comment]
Yes, probably. To be fair, I haven't even used it yet, so you could ignore this altogether.

Depending on this package as a whole isn't that bad after all, I just feel like there are bits and pieces of this package that deserve to be separated. I understand that you don't want to mess around with a bazillion `foundation-*` packages, though.
