### ISSUE TITLE
Add parser combinators

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#89]
I'm currently using attoparsec, but a foundation String based one would be a lot easier. Either wrappers over the attoparsec class, or a port to a new string type, or perhaps even a fresh parser combinator library in the same style.

**Comment by NicolasDP** [comment]
It should not be difficult to add this to foundation.
[memory](https://www.stackage.org/haddock/lts-6.12/memory-0.13/Data-ByteArray-Parse.html) has a nice ByteArray parser. I think we could do something similar, but using `Sequential` and `IndexedCollection` type classes:

```Haskell
type Read a = (IndexedCollection a, Sequential a)

newtype Parser input a = ...
take :: Read a => Size -> Parser a a
element :: Read a => Element a -> Parser a a
```

**Comment by NicolasDP** [comment]
actually, `IndexedCollection` is not even needed...

**Comment by ndmitchell** [comment]
I am not sure whether this should be in the foundation library itself, or a foundation-parser library. I think @vincenthz wanted it in this library, although I'm not sure I would have done that.

**Comment by NicolasDP** [comment]
Parsers and packers are commonly used libraries. It does make sense to have it in the *core* library. We could start with something simple, making use of `Sequential` objects, and see if it outgrows the core package.

**Comment by NicolasDP** [comment]
@ndmitchell I just tried to see how I could re-use what was in `memory` but using `Sequential`. I think, this way, we can cover most of the basic usage.

```Haskell
ghci> let x = "xx abctest" :: String
ghci> parse ((,,) <$> take 2 <*> element ' ' <*> (elements "abc" *> anyElement))
ParseOK ("xx",(),'t') "est"
```

**Comment by ndmitchell** [comment]
I'm not particularly adverse to it being in the core library, certainly, that could be very handy. To be concrete in my particular use case, I'm after basically a subset of `attoparsec`. I don't want to feed in additional data after the fact (although I can see how that is handy). I do want composition (e.g. `>>=`) and choice (e.g. `<|>`). I love the unlimited backtracking meaning I don't have to add `try` everywhere. I do a bunch of `optional` stuff, but otherwise, not that much more. `peekChar` has some in handy a few times.

**Comment by NicolasDP** [comment]
I've written a quick bench: using simple implementation of the parser of the SMTP `EHLO` command.
In the 1st bench, I am using Foundation's `String` and the `Sequential` based Foundation's `Parser.
In the 2nd bench, I am using `Attorparsec` and `ByteString`.

```
benchmarking parse/foundation:EHLO
time                 11.32 μs   (11.14 μs .. 11.49 μs)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 11.38 μs   (11.23 μs .. 11.54 μs)
std dev              535.5 ns   (442.4 ns .. 669.7 ns)
variance introduced by outliers: 57% (severely inflated)

benchmarking parse/attoparsec:EHLO
time                 1.586 μs   (1.562 μs .. 1.611 μs)
                     0.998 R²   (0.998 R² .. 0.999 R²)
mean                 1.601 μs   (1.578 μs .. 1.620 μs)
std dev              70.58 ns   (59.65 ns .. 92.06 ns)
variance introduced by outliers: 59% (severely inflated)
```

**Comment by NicolasDP** [comment]
There are obviously some performance issue to use `Sequential` to write a parser. But it has the advantage of working with any collections.

**Comment by vincenthz** [comment]
I think having a simple basic core parser is useful; its one of those thing people reach for really quickly. Its very likely to be possible to make it much faster, lots of low hanging fruits.

**Comment by vincenthz** [comment]
Also this is somewhat comparing apple and potato here. Real thing to compare would be uvector word8 or attoparsec text interface

**Comment by ndmitchell** [comment]
It's useful even if it's slow to start with. Looking forward to what you guys produce.

**Comment by NicolasDP** [comment]
Ok, my bad, @vincenthz you are right, using `UArray Word8` is better. I also fixed the implementation of the parser with Attoparsec (as it didn't parse it entirely...)

So, `Attoparsec.ByteString` and  `Data.ByteString` vs `Foundation.Parser` and `Foundation.UArray`:

```
Linking compare-libs/Parser ...
benchmarking parse/foundation:EHLO
time                 7.845 μs   (7.773 μs .. 7.922 μs)
                     0.999 R²   (0.998 R² .. 0.999 R²)
mean                 7.861 μs   (7.750 μs .. 8.006 μs)
std dev              410.5 ns   (328.2 ns .. 585.2 ns)
variance introduced by outliers: 63% (severely inflated)

benchmarking parse/attoparsec:EHLO
time                 5.576 μs   (5.509 μs .. 5.651 μs)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 5.573 μs   (5.475 μs .. 5.651 μs)
std dev              287.0 ns   (232.0 ns .. 350.2 ns)
variance introduced by outliers: 63% (severely inflated)
```

**Comment by NicolasDP** [comment]
so really not to bad. I will produce some unit tests and make a pull request later today with what I have already.

**Comment by vincenthz** [comment]
Nice benchmarks, but yeah it's pretty secondary at this stage. Let's an API that make sense in, and then optimise.
