### ISSUE TITLE
Don't use divMod

### ISSUE THREAD

**Issue by treeowl** [haskell-foundation/foundation#93]
`Foundation.Array.Bitmap` uses `divMod`. I'm pretty sure you really want `quotRem` there.

**Comment by vincenthz** [comment]
The index is not going to be negative, so it's not making a difference for exactness, but I agree generally. I suppose it will be solved through the following pending items:

* It's pending a better story with the division class of things, that is (really) loosely related to the Float/Double division not being there either.
* more use of `Offset` and `Size` that are somewhat solving the not accurate use of `Int` everywhere.
